'use client';

import React, { useEffect, useState } from 'react';
import { ANALYSIS_TYPES } from '@/lib/ncs-credits';
import { Printer, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

// Import raw extracted scripts generated by script
import defaultScriptsData from '@/lib/webr/default-scripts.json';

interface Template {
    key: string;
    value: string;
}

export default function AnalysisCodeReport() {
    const [templates, setTemplates] = useState<Record<string, string>>({});
    const [loading, setLoading] = useState(true);
    const defaultScripts = defaultScriptsData as Record<string, string>;

    useEffect(() => {
        const fetchTemplates = async () => {
            try {
                const response = await fetch('/api/admin/analysis-templates');
                const data = await response.json();
                
                if (data.templates) {
                    const templateMap: Record<string, string> = {};
                    data.templates.forEach((t: Template) => {
                        const cleanKey = t.key.replace('r_template_', '');
                        templateMap[cleanKey] = t.value;
                    });
                    setTemplates(templateMap);
                }
            } catch (error) {
                console.error("Failed to load templates", error);
            } finally {
                setLoading(false);
            }
        };
        fetchTemplates();
    }, []);

    const handlePrint = () => {
        window.print();
    };

    if (loading) {
        return <div className="p-10 text-center">Đang tải báo cáo...</div>;
    }

    return (
        <div className="min-h-screen bg-white">
            {/* Action Bar (hidden in print) */}
            <div className="print:hidden p-4 bg-slate-100 border-b border-slate-200 flex items-center justify-between sticky top-0 z-50">
                <Link href="/admin/analysis-code" className="flex items-center gap-2 text-slate-600 hover:text-blue-600 font-medium">
                    <ArrowLeft className="w-4 h-4" /> Bỏ qua
                </Link>
                <button 
                    onClick={handlePrint}
                    className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 text-white font-bold rounded-lg shadow-sm hover:bg-blue-700 transition"
                >
                    <Printer className="w-4 h-4" /> Xuất Báo cáo / Lưu PDF
                </button>
            </div>

            {/* Printable Report Content */}
            <div className="p-8 max-w-4xl mx-auto print:p-0">
                <div className="text-center mb-10">
                    <h1 className="text-3xl font-black text-slate-900 mb-2 print:text-2xl">BÁO CÁO CÔNG THỨC R-ENGINE</h1>
                    <p className="text-slate-500">Hệ thống NCSKIT 2026 - Chi tiết thuật toán và mã nguồn thống kê đang áp dụng.</p>
                    <p className="text-sm text-slate-400 mt-2">Ngày trích xuất: {new Date().toLocaleDateString('vi-VN')}</p>
                </div>

                <div className="space-y-12">
                    {Object.entries(ANALYSIS_TYPES).map(([key, label], index) => {
                        const isOverridden = !!templates[key] && templates[key].trim().length > 0;
                        const activeCode = isOverridden ? templates[key] : (defaultScripts[key] || "Không có code mặc định hệ thống cho thuật toán này.");

                        return (
                            <div key={key} className="break-inside-avoid border border-slate-200 rounded-xl overflow-hidden print:border-none print:shadow-none print:mb-8">
                                <div className="bg-slate-50 p-4 border-b border-slate-200 print:bg-transparent print:border-b-2 print:border-slate-800 print:px-0 flex flex-col md:flex-row justify-between items-start md:items-center">
                                    <h2 className="text-lg font-bold text-slate-800">
                                        {index + 1}. {label} <span className="font-normal text-slate-500 text-sm">({key})</span>
                                    </h2>
                                    <div className="mt-2 md:mt-0">
                                        {isOverridden ? (
                                            <span className="px-2.5 py-1 bg-amber-100/50 text-amber-700 border border-amber-200 text-xs font-bold uppercase rounded print:border-none print:p-0">Đang Custom</span>
                                        ) : (
                                            <span className="px-2.5 py-1 bg-emerald-100/50 text-emerald-700 border border-emerald-200 text-xs font-bold uppercase rounded print:border-none print:p-0">Mặc định</span>
                                        )}
                                    </div>
                                </div>
                                <div className="p-4 bg-slate-900 print:bg-slate-50 print:text-black">
                                    <pre className="text-xs text-indigo-100 font-mono whitespace-pre-wrap leading-relaxed print:text-slate-800 break-words">
                                        {activeCode}
                                    </pre>
                                </div>
                            </div>
                        );
                    })}
                </div>
                
                <div className="mt-12 pt-8 border-t border-slate-200 text-center text-xs text-slate-400 print:block">
                    Tài liệu này được trích xuất tự động từ hệ thống lõi WebR Engine của NCSKIT.
                </div>
            </div>
        </div>
    );
}
