-- =========================================================================
-- NCSKIT 2026 - LONG-FORM EXPERT ARTICLES (FIXED JSON SYNTAX)
-- Use Dollar-Quoting ($$ ... $$) for safe SQL insertion
-- =========================================================================

INSERT INTO "public"."knowledge_articles" ("id", "slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") VALUES 
(
    'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 
    'technology-acceptance-model-tam', 
    'Research Models', 
    'Giải mã Mô hình TAM: Từ lý thuyết đến kịch bản thực chiến Scopus', 
    'Technology Acceptance Model (TAM): The Ultimate Guide', 
    'Bí quyết để bài báo TAM không bị Reviewer gạt: Hãy tích hợp "Tính đổi mới cảm nhận" (Personal Innovativeness) hoặc "Lo âu công nghệ" (Computer Anxiety) như những biến điều tiết để tạo ra sự khác biệt học thuật.', 
    'Expert Insight: To pass Scopus/ISI review with TAM, integrate Personal Innovativeness or Computer Anxiety as moderators to create academic novelty.', 
    $$[
        {"h2_vi":"1. Tại sao TAM vẫn là 'Vua' trong các nghiên cứu chấp nhận công nghệ?","h2_en":"1. Why TAM remains the King?","content_vi":"Dù đã ra đời hơn 3 thập kỷ, mô hình TAM của Fred Davis vẫn giữ vững vị thế nhờ tính tùy biến cực cao. Điểm đắt giá nhất của TAM không nằm ở bản thân nó, mà ở khả năng 'cấy ghép' các nhân tố ngoại lai. Nếu bạn đang làm về #AI, #ChatGPT hay #Fintech, TAM cung cấp một khung sườn hoàn hảo để bạn mở rộng thêm các khía cạnh như Niềm tin (Trust) hay Rủi ro cảm nhận (Perceived Risk).","content_en":"Fred Davis's TAM model persists as an academic staple due to its extreme flexibility. Its true value lies in the 'plug-and-play' nature of external variables, making it ideal for #AI, #Fintech, and #EdTech research."},
        {"h2_vi":"2. Phẫu thuật biến PU và PEOU: Những kịch bản dữ liệu thực tế","h2_en":"2. Deep Dive: PU vs. PEOU","content_vi":"- **Hữu ích cảm nhận (PU):** Là động lực thực dụng. Đáp viên sẽ đánh giá cao mục này nếu công nghệ giúp họ kiếm tiền nhanh hơn hoặc tiết kiệm thời gian.\n- **Dễ sử dụng cảm nhận (PEOU):** Là rào cản tâm lý. Nếu giao diện quá rối (Poor UX), PEOU sẽ thấp, và kéo theo sự sụt giảm của chính PU. Trong phân tích #CFA, hai nhân tố này phải đảm bảo được tính phân biệt (Discriminant Validity) rõ rệt.","content_en":"- **Perceived Usefulness (PU):** The pragmatic driver. Users value tech that directly enhances income or saves time.\n- **Perceived Ease of Use (PEOU):** The psychological barrier. Poor UX tanks PEOU and subsequently PU. Ensure clear #DiscriminantValidity during your #CFA phase."},
        {"h2_vi":"3. Kịch bản chạy Data TAM chuẩn APA trên ncsStat","h2_en":"3. ncsStat Experimental Workflow","content_vi":"Để bài báo 'mượt' nhất, quy trình tại ncsStat sẽ là: Làm sạch Outliers -> Cronbach's Alpha (>0.7) -> EFA -> Hồi quy đa biến. Hãy kiểm tra các hệ số Path Coefficient (Beta) để xem PU hay PEOU mới thực sự là 'kẻ chi phối' hành vi người dùng trong bối cảnh xã hội số Việt Nam. #QuantitativeResearch #Statistics","content_en":"The optimal workflow: Outlier cleaning -> Alpha -> EFA -> Regression. Compare Path Coefficients (Beta) to identify the dominant driver of adoption in specific digital contexts. #SmartPLS #ResearchFramework"}
    ]$$
),
(
    'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 
    'theory-of-planned-behavior-tpb', 
    'Behavioral Research', 
    'Thuyết Hành vi Dự định (TPB): Chìa khóa vàng giải mã Ý định',
    'Theory of Planned Behavior (TPB): The Golden Key to Intention', 
    'Hãy chú ý đến khoảng cách giữa Ý định (Intention) và Hành vi thực tế (Behavior). Nhiều nghiên cứu cho thấy Ý định rất cao nhưng Hành vi lại thấp. Đừng quên đưa biến PBC vào như một biến điều tiết.', 
    'Pay attention to the Intention-Behavior gap. Use Perceived Behavioral Control (PBC) as a moderator to deepen your analysis.', 
    $$[
        {"h2_vi":"1. Từ TRA đến TPB: Bước ngoặt của Icek Ajzen","h2_en":"1. From TRA to TPB: Icek Ajzen's Turning Point","content_vi":"Ban đầu, Thuyết Hành động Hợp lý (TRA) chỉ tập trung vào Thái độ và Chuẩn chủ quan. Tuy nhiên, Ajzen nhận ra rằng con người không luôn có quyền kiểm soát hoàn toàn hành vi của mình (Vd: muốn mua iPhone nhưng không đủ tiền). Do đó, ông đã thêm biến PBC vào năm 1991 để tạo ra TPB.","content_en":"Initially, TRA focused on Attitude and Subjective Norms. Ajzen realized humans lack total control over behaviors (e.g., wanting an iPhone but lacking funds), so he added Perceived Behavioral Control (PBC) in 1991."},
        {"h2_vi":"2. Ba chân kiềng của Ý định hành vi","h2_en":"2. The Three Components of Intention","content_vi":"- Thái độ (Attitude): Đánh giá tích cực hay tiêu cực về hành vi.\n- Chuẩn chủ quan (Subjective Norm): Áp lực từ những người xung quanh (gia đình, bạn bè, đồng nghiệp).\n- Kiểm soát hành vi cảm nhận (PBC): Niềm tin vào khả năng thực hiện hành vi của bản thân mình.","content_en":"- Attitude: Positive or negative evaluation.\n- Subjective Norm: Pressure from social circles.\n- PBC: Self-belief in the ability to perform the behavior."},
        {"h2_vi":"3. Ứng dụng trong Marketing và Tâm lý học","h2_en":"3. Applications in Marketing and Psychology","content_vi":"TPB được dùng để giải thích hầu hết mọi hành vi: Từ việc khách hàng chọn mua thực phẩm hữu cơ, sinh viên quyết định khởi nghiệp, đến cả việc người dân tuân thủ quy định đeo khẩu trang. Trong phân tích trên ncsStat, TPB thường được sử dụng như một khung lý thuyết nền vững chắc.","content_en":"TPB explains diverse behaviors: Buying organic food, student entrepreneurship, or compliance with health regulations. ncsStat users often use TPB as a robust framework."},
        {"h2_vi":"4. Phân tích Mediation (Biến trung gian) trong TPB","h2_en":"4. Mediation Analysis in TPB","content_vi":"Một xu hướng hiện đại là nghiên cứu cách các biến nhân khẩu học hoặc các yếu tố ngoại vi tác động đến Ý định THÔNG QUA ba nhân tố của TPB. ncsStat hỗ trợ bạn chạy kiểm định Sobel hoặc Bootstrapping để xác định chính xác hiệu ứng trung gian này.","content_en":"A modern trend is researching how external factors impact Intention VIA TPB components. ncsStat supports Sobel and Bootstrapping tests to identify these mediation effects."}
    ]$$
),
(
    'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', 
    'signaling-theory-research', 
    'Market Strategy', 
    'Lý thuyết Tín hiệu (Signaling Theory): Khi Hành động thay cho lời nói', 
    'Signaling Theory: Actions Speak Louder Than Words', 
    'Khi làm về Signaling, hãy phân rõ ai là Người phát tín hiệu (Sender) và ai là Người nhận (Receiver). Một tín hiệu không có chi phí (free signal) thường bị coi là cheap talk và không có giá trị.', 
    'Clarify the Sender and Receiver. A free signal is often dismissed as cheap talk and holds no value for investors or search engines.', 
    $$[
        {"h2_vi":"1. Michael Spence và Giải Nobel Kinh tế","h2_en":"1. Michael Spence and the Nobel Prize","content_vi":"Signaling Theory ra đời từ nghiên cứu về thị trường lao động của Michael Spence (1973). Tại sao bằng cấp lại quan trọng ngay cả khi kiến thức trong trường không dùng tới? Vì tấm bằng là một tín hiệu cực kỳ tốn kém về thời gian và trí tuệ, báo hiệu cho nhà tuyển dụng rằng ứng viên là người có năng lực.","content_en":"Born from Michael Spence's 1973 labor market research. Degrees matter because they are a costly signal of time and intelligence, signaling competence to employers."},
        {"h2_vi":"2. Cơ chế hoạt động: Sender - Signal - Receiver","h2_en":"2. Mechanism: Sender - Signal - Receiver","content_vi":"Trong thị trường bất đối xứng thông tin, người bán biết rõ chất lượng sản phẩm hơn người mua. Để thuyết phục, người bán phải phát đi các tín hiệu (Vd: Bảo hành 10 năm, chứng chỉ chất lượng ISO, hoặc đánh giá 5 sao từ chuyên gia). Nếu tín hiệu đủ mạnh, người nhận (Receiver) sẽ thay đổi nhận thức.","content_en":"In asymmetric markets, sellers know quality better than buyers. To persuade, sellers must send signals (e.g., 10-year warranties, ISO certificates, expert reviews). Strong signals change receiver perceptions."},
        {"h2_vi":"3. Tại sao nội dung này lại quan trọng cho Marketing hiện đại?","h2_en":"3. Why It Matters for Modern Marketing","content_vi":"Trong kỷ nguyên số, Lòng tin là mặt hàng xa xỉ. Thương hiệu mạnh chính là một hệ thống tín hiệu phức tạp giúp giảm rủi ro cảm nhận của khách hàng. ncsStat giúp bạn đo lường mức độ tác động của các tín hiệu (như CSR, Thương hiệu cá nhân) đến hành vi trung thành.","content_en":"In the digital age, Trust is luxury. Strong branding is a complex signal system reducing perceived risk. ncsStat helps measure signal impacts (like CSR, Personal Branding) on loyalty."},
        {"h2_vi":"4. Cách kiểm định Lý thuyết Tín hiệu trên nền tảng ncsStat","h2_en":"4. Testing Signaling Theory on ncsStat","content_vi":"Bạn có thể sử dụng phương pháp Thực nghiệm hoặc khảo sát bảng hỏi. Với ncsStat, bạn dễ dàng so sánh sự khác biệt giữa các nhóm (T-test, ANOVA) để thấy rõ sức mạnh của việc có và không có tín hiệu ảnh hưởng thế nào đến Ý định mua/tin tưởng.","content_en":"Use experimental designs or surveys. With ncsStat, compare groups (T-test, ANOVA) to see how signals affect purchase intent and trust."}
    ]$$
),
(
    'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80', 
    'cronbach-alpha', 
    'Preliminary Analysis', 
    'Kiểm định Cronbach''s Alpha: Nghệ thuật đo lường sự nhất quán', 
    'Cronbach''s Alpha Reliability Test: The Symphony of Internal Consistency', 
    'Một hệ số Alpha quá cao (>0.95) thường là "tín hiệu xấu" cho thấy các câu hỏi đang bị lặp lại vô nghĩa. Hãy làm mới bảng hỏi bằng các sắc thái ngôn ngữ khác nhau để dữ liệu "sống" hơn.', 
    'Expert Tip: An Alpha > 0.95 is often a red flag for redundancy. Diversify your item phrasing to capture authentic respondent nuances.', 
    $$[
        {"h2_vi":"1. Cronbach's Alpha: Bản giao hưởng của sự tin cậy","h2_en":"1. The Symphony of Reliability","content_vi":"Khi bạn thiết kế một bảng hỏi (scale), Alpha chính là 'giám khảo' thẩm định xem các câu hỏi có đang cùng nói về một chủ đề hay không. Trái ngược với suy nghĩ thông thường, Alpha không đo tính đúng đắn của dữ liệu, mà đo **tính nhất quán**. Nếu một người đồng ý với câu 'Tôi hài lòng', họ cũng nên đồng ý với câu 'Tôi sẽ quay lại'. Nếu không, thang đo của bạn đang bị 'nhiễu'. #Reliability #DataCleaning","content_en":"Alpha acts as the ultimate judge of internal consistency. It doesn't verify data 'truth', but rather 'consistency'. If users agree with 'I am satisfied', they must logically favor 'I will return'. Inconsistencies indicate scale noise. #Psychometrics"},
        {"h2_vi":"2. Bẫy Item-Total Correlation: Cách dọn dẹp biến 'rác'","h2_en":"2. Cleaning 'Garbage' Items","content_vi":"Đừng chỉ nhìn vào con số Alpha tổng. Hãy soi vào cột **Corrected Item-Total Correlation**. Nếu một biến có hệ số < 0.3, nó giống như một nốt nhạc phô trong bản nhạc. Loại bỏ nó sẽ giúp bản nhạc (nhân tố) của bạn trong trẻo và chuyên nghiệp hơn hẳn khi trình hội đồng. Tại ncsStat, chúng tôi tự động đánh dấu các biến này để bạn xử lý trong 1 nốt nhạc. #SPSS #Amos #DataAnalysis","content_en":"Look beyond the global Alpha. The 'Corrected Item-Total Correlation' reveals the outliers. Any item < 0.3 is 'statistically dissonant' and should be purged to ensure a clean factor structure for your thesis. #ScopusTips"},
        {"h2_vi":"3. Khi nào thì Alpha > 0.6 được chấp nhận?","h2_en":"3. When is 0.6 Acceptable?","content_vi":"Trong các nghiên cứu mang tính khám phá (Exploratory), nơi bạn là người tiên phong xây dựng thang đo, mức 0.6 là 'tấm vé thông hành' hợp lệ. Đừng quá cứng nhắc ép lên 0.7 bằng cách xóa sạch biến, vì bạn sẽ làm mất đi tính đa diện của khái niệm nghiên cứu. #AcademicInsight #MastersThesis","content_en":"In pioneer/exploratory research where new scales are birthed, 0.6 is a valid passport. Resilience in methodology is better than losing construct richness just to force a 0.7. #ExpertGuidance"}
    ]$$
),
(
    'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8011', 
    'efa-factor-analysis', 
    'Factor Analysis', 
    'Phân tích nhân tố khám phá (EFA): Hướng dẫn thực chiến từ KMO đến Ma trận xoay', 
    'Exploratory Factor Analysis (EFA): Discovering Inner Structures', 
    '💡 KINH NGHIỆM: Khi chạy EFA, hãy đặc biệt chú ý đến hiện tượng "tải chéo" (cross-loading). Nếu một biến tải lên 2 nhân tố với độ chênh lệch hệ số < 0.3, hãy xem xét loại bỏ biến đó để đảm bảo giá trị hội tụ và phân biệt của mô hình.', 
    'EXPERT TIP: Watch out for cross-loadings (>0.3 difference). Remove problematic items to ensure clean factor discrimination and convergence.', 
    $$[
        {"h2_vi":"1. Phân tích nhân tố khám phá (EFA) là gì?","h2_en":"1. Why run EFA after Alpha?","content_vi":"**Phân tích nhân tố khám phá (EFA)** là một kỹ thuật thống kê dùng để rút gọn một tập hợp gồm nhiều biến quan sát thành một số ít các nhóm nhân tố có ý nghĩa hơn. Nếu Cronbach's Alpha giúp kiểm tra xem các câu hỏi có 'hợp nhau' không, thì EFA giúp xác định các câu hỏi đó thực chất đang 'nói về chủ đề gì'. Ví dụ: bạn ném 20 câu hỏi vào máy, EFA sẽ tự động gom chúng thành 4 nhóm: Chi phí, Chất lượng, Dịch vụ và Tiện ích dựa trên phản hồi thực tế của đáp viên.","content_en":"EFA reduces multiple variables into a few meaningful factors. It groups items objectively based on respondent patterns. If Alpha tests consistency, EFA tests structure—grouping 20 items into clear clusters like Cost, Quality, and Service."},
        {"h2_vi":"2. Các chỉ số gác cổng: KMO và Kiểm định Bartlett","h2_en":"2. KMO and Bartlett's Test: The Ticket In","content_vi":"Trước khi xem kết quả các nhóm, bạn bắt buộc phải vượt qua hai bài kiểm tra 'tư cách' dữ liệu:\n- **Hệ số KMO (Kaiser-Meyer-Olkin):** Đây là chỉ số đo lường sự thỏa đáng của mẫu. Giá trị KMO phải đạt từ **0.5 trở lên** thì kết quả EFA mới đáng tin cậy.\n- **Kiểm định Bartlett:** Mức ý nghĩa Sig. phải **nhỏ hơn 0.05**. Chỉ số này chứng minh rằng các biến quan sát trong tổng thể có tương quan với nhau và việc phân tích nhân tố là hoàn toàn phù hợp.","content_en":"Mandatory metrics: 1. KMO index must be >= 0.5 to ensure sampling adequacy. 2. Bartlett's Test Sig. must be < 0.05, proving the correlation matrix is suitable for factor extraction."},
        {"h2_vi":"3. Tiêu chuẩn trích nhân tố: Eigenvalue và Phương sai trích","h2_en":"3. Eigenvalues and Variance Explained","content_vi":"Làm sao để biết nên chia thành bao nhiêu nhân tố? ncsStat sẽ dựa vào:\n- **Hệ số Eigenvalue:** Theo tiêu chuẩn Kaiser, chúng ta chỉ giữ lại các nhân tố có Eigenvalue **lớn hơn 1**. Đây là các nhân tố có sức mạnh giải thích dữ liệu thực sự.\n- **Tổng phương sai trích (Total Variance Explained):** Giá trị này nên đạt từ **50% trở lên**. Nó cho biết các nhân tố được rút ra giải thích được bao nhiêu phần trăm sự biến thiên của dữ liệu gốc. Nếu đạt 60%, bài nghiên cứu của bạn sẽ cực kỳ thuyết phục trước hội đồng.","content_en":"Extraction Criteria: 1. Eigenvalues > 1 (Kaiser Criterion) identifies meaningful factors. 2. Total Variance Explained >= 50% (ideally 60%) ensures the factors represent a majority of the original data's information."},
        {"h2_vi":"4. Ma trận xoay: Đọc vị Factor Loading và Tải chéo","h2_en":"4. Rotated Matrix & Cross-loadings","content_vi":"Ma trận xoay (**Rotated Component Matrix**) là phần quan trọng nhất để trình bày trong bài báo. \n- **Hệ số tải nhân tố (Factor Loading):** Phải lớn hơn **0.5** để chứng minh biến quan sát có ý nghĩa thực tế.\n- **Tải chéo (Cross-loading):** Một biến rắc rối sẽ hiện diện ở cả hai cột nhân tố khác nhau. Quy tắc vàng là độ lệch giữa hai hệ số tải phải lớn hơn **0.3**. Nếu không, biến đó đang bị 'lưỡng tính' và cần bị loại bỏ để làm sạch mô hình nghiên cứu.","content_en":"The Rotated Matrix is your primary evidence. Items should have loadings >= 0.5. Beware of Cross-loading where an item loads heavily on two factors; a gap > 0.3 is required to maintain discriminant validity."},
        {"h2_vi":"5. Lộ trình thực hiện EFA chuẩn SEO trên ncsStat","h2_en":"5. ncsStat Execution Workflow","content_vi":"Quy trình 3 bước chuẩn tại ncsStat:\n1. Chọn module 'Phân tích nhân tố EFA'.\n2. Cài đặt các tham số: Phép trích Principal Components, Phép xoay Varimax hoặc Promax.\n3. Kiểm tra các điều kiện KMO, Eigenvalue và Ma trận xoay. Xuất kết quả sang Word với định dạng bảng biểu chuẩn APA 7 để hoàn tất báo cáo khoa học.","content_en":"EFA workflow on ncsStat: 1. Select EFA module. 2. Configure Extraction (Principal Components) and Rotation (Varimax/Promax). 3. Verify KMO and Matrices, then export as APA 7 tables."}
    ]$$
),
(
    'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f801122', 
    'regression-vif-multicollinearity', 
    'Impact Analysis', 
    'Hồi quy tuyến tính Đa biến: Cách kiểm soát VIF và đa cộng tuyến', 
    'Multiple Regression & VIF: Predicting the Future', 
    '📝 LƯU Ý: R-Square (R bình phương) cho biết độ mạnh của mô hình, nhưng đừng quên kiểm tra VIF. Nếu VIF > 10, kết quả dự báo của bạn đang bị sai lệch hoàn toàn do các biến độc lập đang "tự dẫm đạp" lên nhau.', 
    'EXPERT NOTE: R-Square measures model strength, but VIF is the safety check. If VIF > 10, your predictions are skewed by heavy multicollinearity.', 
    $$[
        {"h2_vi":"1. Tại sao Hồi quy tuyến tính là trái tim của nghiên cứu định lượng?","h2_en":"1. Why Regression is the King of Statistics","content_vi":"**Hồi quy tuyến tính đa biến** giúp chúng ta trả lời câu hỏi: Yếu tố nào có tác động mạnh nhất? Ví dụ, bạn muốn biết trong 3 yếu tố 'Giá cả', 'Chất lượng', 'Thương hiệu', cái nào quyết định 80% 'Hành vi mua hàng'. Phân tích hồi quy sẽ cho bạn con số Beta cụ thể để đo lường độ mạnh yếu của từng tác động này, giúp đưa ra các kiến nghị chính xác cho doanh nghiệp.","content_en":"Multiple Regression answers: 'Which factor impacts the outcome most?'. It provides Beta weights to compare the influence of variables like Price, Quality, and Brand on Purchase Intention, enabling data-driven decision making."},
        {"h2_vi":"2. R-Square: Chỉ số đo lường sức mạnh dự báo","h2_en":"2. R-Square: Predictive Power","content_vi":"Khi đọc bảng kết quả trên ncsStat, hãy tìm chỉ số **Adjusted R-Square** (R bình phương hiệu chỉnh). Nếu con số này là 0.65, có nghĩa là các biến độc lập trong mô hình giải thích được 65% sự thay đổi của biến phụ thuộc. Trong khoa học xã hội, một giá trị R-Square trên 0.4 đã được coi là rất thành công và có ý nghĩa thực tiễn cao.","content_en":"Find 'Adjusted R-Square' in your results. A value of 0.65 means your model explains 65% of the dependent variable's variance. In social sciences, an R-Square > 0.4 is generally considered a strong and successful model."},
        {"h2_vi":"3. Kiểm soát Đa cộng tuyến qua hệ số VIF","h2_en":"3. Multicollinearity & the VIF Shadow","content_vi":"Đa cộng tuyến là hiện tượng các biến độc lập tương quan quá mạnh với nhau, làm sai lệch kết quả hồi quy. Để kiểm soát điều này, chúng ta sử dụng hệ số **VIF (Variance Inflation Factor)**:\n- **VIF < 2:** Mô hình cực kỳ an toàn.\n- **VIF < 5:** Chấp nhận được ở mức tốt.\n- **VIF > 10:** Đa cộng tuyến nghiêm trọng. Bạn cần loại bỏ biến có VIF cao nhất hoặc gộp các biến tương quan mạnh lại với nhau rồi chạy lại mô hình.","content_en":"Multicollinearity skews regression coefficients. Use VIF (Variance Inflation Factor) to check: VIF < 2 is ideal; VIF < 5 is acceptable; VIF > 10 indicates a serious problem requiring item removal or merger."},
        {"h2_vi":"4. Đọc hệ số Beta: Ai là người có tầm ảnh hưởng lớn nhất?","h2_en":"4. Fate Decision: P-value Sig & Beta Weights","content_vi":"Cuối cùng, hãy nhìn vào cột **Standardized Beta** và **Sig.**. \n- Một biến chỉ có ý nghĩa nếu **Sig. < 0.05**. \n- Trong các biến có ý nghĩa, biến nào có hệ số Beta trị tuyệt đối lớn nhất thì đó là biến có tác động mạnh nhất. ncsStat sẽ tự động làm nổi bật các biến này để bạn dễ dàng đưa vào nhận định luận văn chuẩn APA.","content_en":"Focus on 'Standardized Beta' and 'Sig.'. A variable is only significant if Sig. < 0.05. Among significant variables, the one with the highest absolute Beta has the strongest impact. ncsStat highlights these for easy APA reporting."}
    ]$$
)
ON CONFLICT (slug) DO UPDATE SET 
    title_vi = EXCLUDED.title_vi,
    title_en = EXCLUDED.title_en,
    expert_tip_vi = EXCLUDED.expert_tip_vi,
    expert_tip_en = EXCLUDED.expert_tip_en,
    content_structure = EXCLUDED.content_structure;
