-- =========================================================================
-- NCSKIT 2026 - LONG-FORM EXPERT ARTICLES (FIXED JSON SYNTAX)
-- Use Dollar-Quoting ($$ ... $$) for safe SQL insertion
-- =========================================================================

INSERT INTO "public"."knowledge_articles" ("id", "slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") VALUES 
(
    'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 
    'technology-acceptance-model-tam', 
    'Research Models', 
    'Mô hình Chấp nhận Công nghệ (TAM): Hướng dẫn Chuyên sâu và Kịch bản chạy Data (Toàn tập)', 
    'Technology Acceptance Model (TAM): The Ultimate Guide', 
    'Đừng chỉ dừng lại ở mô hình gốc năm 1989. Để bài báo đạt chuẩn Scopus/ISI, bạn nên tích hợp TAM với các yếu tố như Trust (Niềm tin), Perceived Risk (Rủi ro cảm nhận) hoặc Mobility (Tính di động) để tạo ra sự đóng góp mới (Novelty).', 
    'Move beyond the 1989 original. For Scopus/ISI standards, integrate TAM with Trust, Perceived Risk, or context-specific factors like Mobility.', 
    $$[
        {"h2_vi":"1. Tổng quan vĩ mô về TAM và Nguồn gốc Kỷ nguyên Số (1000+ words scope)","h2_en":"1. Macro Overview of TAM and Digital Era Origins","content_vi":"Mô hình Chấp nhận Công nghệ (Technology Acceptance Model - TAM) do Tiến sĩ Fred Davis tiên phong đề xuất vào năm 1989 tại MIT. Hiện tại, TAM được coi là 'kim chỉ nam' vĩ đại nhất trong các nghiên cứu về chuỗi hành vi sử dụng Công Nghệ Thông Tin (IT) Hệ thống quản trị (MIS), công nghệ di động và kinh tế số. Được xây dựng dựa trên nền tảng của Thuyết Hành động Hợp lý (Theory of Reasoned Action - TRA) của Fishbein và Ajzen, TAM tối giản hóa các ràng buộc phức tạp của tâm lý học hành vi con người thành hai yếu tố tiên quyết rõ ràng minh bạch nhất: Sự hữu ích cảm nhận được (Perceived Usefulness - PU) và Tương tác dễ dàng cảm nhận được (Perceived Ease of Use - PEOU). Trong hơn 3 thập kỷ, TAM đã được kiểm chứng trên hàng triệu tập khách hàng, từ việc sinh viên dùng E-learning, khách hàng dùng Mobile Banking, cho đến nhân viên văn phòng chuyển đổi sang AI và ChatGPT. Sức sống của TAM nằm ở sự đơn giản, tính tùy biến cực cao, cho phép các tiến sĩ, thạc sĩ dễ dàng 'cấy ghép' thêm vô số các biến ngoại lai (External Variables) để đo lường bối cảnh cụ thể của tổ chức.","content_en":"The Technology Acceptance Model (TAM) was proposed by Fred Davis in 1989. Over 30 years later, it remains the 'common language' for seekers in MIS and Business Management wanting to understand tech adoption."},
        {"h2_vi":"2. Giải phẫu cấu trúc Lõi: PU và PEOU","h2_en":"2. Anatomical Structure: PU and PEOU","content_vi":"Cấu trúc lõi của TAM luôn đảm bảo tính bền vững của các mối quan hệ (Structural Links):\n- Sự hữu ích cảm nhận (PU - Perceived Usefulness): Được định nghĩa là mức độ mà một cá nhân tin rằng, bằng cách sử dụng một hệ thống cụ thể, hiệu suất công việc hay cuộc sống của họ sẽ được tự động nâng cao rõ rệt. PU phản ánh tính thực tế (Pragmatic Value). Nếu một App đẹp nhưng không giải quyết được vấn đề thực tiễn, PU sẽ tụt thảm hại, kéo theo sự diệt vong của sản phẩm.\n- Sự dễ sử dụng cảm nhận (PEOU - Perceived Ease of Use): Là mức độ mà người dùng tin rằng việc tiếp xúc và làm chủ công nghệ mới hầu như không đòi hỏi quá nhiều hao tổn về chất xám hay sức lực (Free of effort). \n- Mối quan hệ tương hỗ: Trong hệ thống TAM, PEOU đóng vai trò như một đòn bẩy kép. Nó không chỉ tác động trực tiếp đến Thái độ (Attitude) và Ý định hành vi (BI), mà còn có tác động dương(+) trực tiếp lên chính PU. Nói cách khác: 'Cái gì càng dễ dùng, người ta càng nhanh chóng nhận ra sự hữu ích của nó'.","content_en":"- Perceived Usefulness (PU): The degree to which a user believes tech improves performance.\n- Perceived Ease of Use (PEOU): The degree to which a user believes tech requires minimal effort. PEOU often impacts PU: ease leads to usefulness."},
        {"h2_vi":"3. Sự tiến hóa: TAM2, TAM3 và Kỷ nguyên UTAUT","h2_en":"3. Evolution: TAM2, TAM3, and UTAUT","content_vi":"Khoa học không bao giờ đứng yên. Dù TAM rất tuyệt vời, nhưng Davis đã nhận ra rằng PU và PEOU chưa đủ để giải thích hoàn toàn Ý định trong môi trường làm việc ép buộc. Do đó:\n- TAM2 (Venkatesh & Davis, 2000): Bổ sung thêm các yếu tố Xã hội học (Social Influence Variables) bảo gồm Chuẩn chủ quan (Subjective Norm), Hình ảnh cá nhân (Image), Tính tự nguyện (Voluntariness), cùng các yếu tố thuộc về Hệ thống như Đặc tính công việc (Job Relevance) và Mức độ tương thích (Output Quality).\n- TAM3 (Venkatesh & Bala, 2008): Lại là một bước nhảy vọt khi tập trung giải phẫu 100% vào nguồn gốc của PEOU. Nó chứng minh rằng Trải nghiệm quá khứ (Computer Playfulness), Tính tự tôn thiết bị (Computer Self-efficacy) và Lo âu công nghệ (Computer Anxiety) đóng vai trò điều hướng người dùng.\n- Đỉnh cao UTAUT (2003): Là sự tổng hòa vĩ đại của 8 hệ thống lý thuyết (TRA, TAM, TPB...). UTAUT cho ra đời 4 trụ cột: Hiệu quả kỳ vọng (Performance Expectancy), Nỗ lực kỳ vọng (Effort Expectancy), Ảnh hưởng xã hội (Social Influence) và Điều kiện thuận lợi (Facilitating Conditions), giúp cho hiệu suất dự phân (Khả năng giải thích phương sai R-square) đạt ngưỡng khổng lồ (lên tới 70% so với 40% của nguyên bản TAM).","content_en":"TAM evolved into TAM2 (adding social factors like Subjective Norms) and TAM3 (focusing on PEOU determinants). Finally, UTAUT (2003) integrated 8 theories, achieving 70% predictive accuracy."},
        {"h2_vi":"4. Các kịch bản mở rộng (Extensions) nâng chuẩn Scopus / ISI","h2_en":"4. Extensions for Scopus / ISI Standards","content_vi":"Để bài luận văn, Luận án Tiến sĩ hoặc bài báo ISI của bạn được Reviewer (người phản biện) đánh giá cao về tính mới (Novelty), tuyệt đối không được bê nguyên xi mô hình cũ. Hãy 'độ' thêm các biến số sao cho phù hợp với thời đại 4.0:\n- Tích hợp 'Trust' (Niềm tin) & 'Perceived Risk' (Rủi ro cảm nhận): Khi bạn nghiên cứu về FinTech, Ví điện tử hay Thương mại điện tử, Rủi ro tài chính, Rủi ro bảo mật là cực kỳ hiện hữu. Hãy biến Trust thành Biến trung gian (Mediator) hoặc Rủi ro thành biến cản trở (Negative independent variable).\n- Tích hợp Kích thích - Phản ứng (S-O-R Model): Bạn có thể cho phép Giao diện App (Visual Design), Mức độ cá nhân hóa (Personalization) làm biến kích thích đầu vào (Stimuli), tác động tới PU/PEOU (Organism) dẫn đến sự hình thành Hành động Mua hàng (Response).\n- Biến Điều Tiết (Moderators): Sự kỳ diệu của thống kê nằm ở việc phát hiện ra rằng 'Tính cách khác nhau sẽ dẫn đến sự lựa chọn khác nhau'. Trên nền tảng ncsStat, hãy sử dụng Phân tích Đa nhóm (Multi-group Analysis / ANOVA) để kiểm tra xem Giới tính (Nam/Nữ) hay Độ tuổi (Gen Z vs Gen X) sẽ làm thay đổi độ mạnh yếu của đường dẫn từ PU -> BI hay không. Người trẻ thường quan tâm PEOU, trong khi người lớn tuổi quan tâm PU và Rủi ro.","content_en":"Integrate TAM with Trust for Fintech, use SOR models for e-commerce, and utilize Demographic Moderators (Age, Gender) to uncover deeper narrative insights and secure high Scopus journal acceptances."},
        {"h2_vi":"5. Lộ trình Phân tích Dữ liệu TAM chuẩn APA Thực Chiến với ncsStat","h2_en":"5. Practical Data Analysis Workflow on ncsStat","content_vi":"Để minh chứng mô hình TAM có ý nghĩa thống kê trên thực tế tại thị trường Việt Nam, hãy làm theo quy trình tinh gọn 4 bước trên hệ thống máy chủ ncsStat:\n\nBƯỚC 1: LÀM SẠCH VÀ MÔ TẢ (Descriptive Statistics)\n- Lọc Outliers ra khỏi dữ liệu thô. Chạy Tần số để trình bày Demographic của mẫu (VD: 60% nữ, 40% nam). Điều này giúp Reviewer thấy được sự minh bạch của dữ liệu thu thập.\n\nBƯỚC 2: CỦNG CỐ CÔNG CỤ ĐO LƯỜNG (Reliability & Factor Analysis)\n- Cronbach's Alpha: Chạy Alpha cho PU, PEOU, BI. Yêu cầu Alpha > 0.70. Nếu biến PU3 làm giảm độ tin cậy Alpha (Nhìn vào cột Item-Total Correlation < 0.3), hãy thẳng tay loại bỏ biến đó ngay trong lần đo đầu tiên.\n- EFA (Exploratory Factor Analysis): Tách cấu trúc nhân tố. Sử dụng phương pháp trích xuất Principal Component, phép xoay Promax hoặc Varimax. Hệ số KMO phải >= 0.5; Bartlett Test phải mang ý nghĩa (p < 0.05). Factor Loadings của biến quan sát (VD: PU1) phải tựu trung mượt mà trên cùng một cột và chỉ số tải > 0.5.\n\nBƯỚC 3: KIỂM ĐỊNH MÔ HÌNH CẤU TRÚC (Regression Analysis)\n- Vào tab Regression, đưa Ý định (BI) vào mục Dependent, và PU, PEOU vào Independent. Xem xét chỉ số VIF, nếu VIF < 3 là cấu trúc dữ liệu cực kỳ tuyệt vời (không có đa cộng tuyến).\n- Đọc hệ số Beta (Standardized Beta): Giá trị Beta càng cao, mũi tên tác động trong hình vẽ (Path diagram) càng đậm. Xác nhận xem P-value (Sig) có < 0.05 để bác bỏ giả thuyết Không (H0) và chấp nhận Giả thuyết Nghiên cứu (H1) hay không.\n\nBƯỚC 4: BÁO CÁO KẾT QUẢ THEO APA 7TH EDITION\n- ncsStat hỗ trợ kết xuất (Export) thẳng các bảng biểu Thống kê định dạng theo chuẩn APA toàn cầu. Dán trực tiếp bảng này vào Microsoft Word mà không cần tự kẻ bảng rườm rà. Chú ý luôn viết In nghiêng các trị số t, p, F. Ví dụ: 'Sự hữu ích cảm nhận (PU) đã tác động thuận chiều mạnh nhất tới Ý định sử dụng thiết bị AI (β = 0.45, t = 6.82, p < 0.001)'.","content_en":"Run a robust workflow on ncsStat: 1. Clean Data & Outliers; 2. Cronbach Alpha & EFA Extrapolations (ensuring Validity); 3. Regression Analysis (monitoring VIF and P-Values < 0.05); 4. Report via one-click APA compliant table generation directly into Word."}
    ]$$
),
(
    'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 
    'theory-of-planned-behavior-tpb', 
    'Behavioral Research', 
    'Thuyết Hành vi Dự định (TPB): Chìa khóa vàng giải mã Ý định',
    'Theory of Planned Behavior (TPB): The Golden Key to Intention', 
    'Hãy chú ý đến khoảng cách giữa Ý định (Intention) và Hành vi thực tế (Behavior). Nhiều nghiên cứu cho thấy Ý định rất cao nhưng Hành vi lại thấp. Đừng quên đưa biến PBC vào như một biến điều tiết.', 
    'Pay attention to the Intention-Behavior gap. Use Perceived Behavioral Control (PBC) as a moderator to deepen your analysis.', 
    $$[
        {"h2_vi":"1. Từ TRA đến TPB: Bước ngoặt của Icek Ajzen","h2_en":"1. From TRA to TPB: Icek Ajzen's Turning Point","content_vi":"Ban đầu, Thuyết Hành động Hợp lý (TRA) chỉ tập trung vào Thái độ và Chuẩn chủ quan. Tuy nhiên, Ajzen nhận ra rằng con người không luôn có quyền kiểm soát hoàn toàn hành vi của mình (Vd: muốn mua iPhone nhưng không đủ tiền). Do đó, ông đã thêm biến PBC vào năm 1991 để tạo ra TPB.","content_en":"Initially, TRA focused on Attitude and Subjective Norms. Ajzen realized humans lack total control over behaviors (e.g., wanting an iPhone but lacking funds), so he added Perceived Behavioral Control (PBC) in 1991."},
        {"h2_vi":"2. Ba chân kiềng của Ý định hành vi","h2_en":"2. The Three Components of Intention","content_vi":"- Thái độ (Attitude): Đánh giá tích cực hay tiêu cực về hành vi.\n- Chuẩn chủ quan (Subjective Norm): Áp lực từ những người xung quanh (gia đình, bạn bè, đồng nghiệp).\n- Kiểm soát hành vi cảm nhận (PBC): Niềm tin vào khả năng thực hiện hành vi của bản thân mình.","content_en":"- Attitude: Positive or negative evaluation.\n- Subjective Norm: Pressure from social circles.\n- PBC: Self-belief in the ability to perform the behavior."},
        {"h2_vi":"3. Ứng dụng trong Marketing và Tâm lý học","h2_en":"3. Applications in Marketing and Psychology","content_vi":"TPB được dùng để giải thích hầu hết mọi hành vi: Từ việc khách hàng chọn mua thực phẩm hữu cơ, sinh viên quyết định khởi nghiệp, đến cả việc người dân tuân thủ quy định đeo khẩu trang. Trong phân tích trên ncsStat, TPB thường được sử dụng như một khung lý thuyết nền vững chắc.","content_en":"TPB explains diverse behaviors: Buying organic food, student entrepreneurship, or compliance with health regulations. ncsStat users often use TPB as a robust framework."},
        {"h2_vi":"4. Phân tích Mediation (Biến trung gian) trong TPB","h2_en":"4. Mediation Analysis in TPB","content_vi":"Một xu hướng hiện đại là nghiên cứu cách các biến nhân khẩu học hoặc các yếu tố ngoại vi tác động đến Ý định THÔNG QUA ba nhân tố của TPB. ncsStat hỗ trợ bạn chạy kiểm định Sobel hoặc Bootstrapping để xác định chính xác hiệu ứng trung gian này.","content_en":"A modern trend is researching how external factors impact Intention VIA TPB components. ncsStat supports Sobel and Bootstrapping tests to identify these mediation effects."}
    ]$$
),
(
    'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', 
    'signaling-theory-research', 
    'Market Strategy', 
    'Lý thuyết Tín hiệu (Signaling Theory): Khi Hành động thay cho lời nói', 
    'Signaling Theory: Actions Speak Louder Than Words', 
    'Khi làm về Signaling, hãy phân rõ ai là Người phát tín hiệu (Sender) và ai là Người nhận (Receiver). Một tín hiệu không có chi phí (free signal) thường bị coi là cheap talk và không có giá trị.', 
    'Clarify the Sender and Receiver. A free signal is often dismissed as cheap talk and holds no value for investors or search engines.', 
    $$[
        {"h2_vi":"1. Michael Spence và Giải Nobel Kinh tế","h2_en":"1. Michael Spence and the Nobel Prize","content_vi":"Signaling Theory ra đời từ nghiên cứu về thị trường lao động của Michael Spence (1973). Tại sao bằng cấp lại quan trọng ngay cả khi kiến thức trong trường không dùng tới? Vì tấm bằng là một tín hiệu cực kỳ tốn kém về thời gian và trí tuệ, báo hiệu cho nhà tuyển dụng rằng ứng viên là người có năng lực.","content_en":"Born from Michael Spence's 1973 labor market research. Degrees matter because they are a costly signal of time and intelligence, signaling competence to employers."},
        {"h2_vi":"2. Cơ chế hoạt động: Sender - Signal - Receiver","h2_en":"2. Mechanism: Sender - Signal - Receiver","content_vi":"Trong thị trường bất đối xứng thông tin, người bán biết rõ chất lượng sản phẩm hơn người mua. Để thuyết phục, người bán phải phát đi các tín hiệu (Vd: Bảo hành 10 năm, chứng chỉ chất lượng ISO, hoặc đánh giá 5 sao từ chuyên gia). Nếu tín hiệu đủ mạnh, người nhận (Receiver) sẽ thay đổi nhận thức.","content_en":"In asymmetric markets, sellers know quality better than buyers. To persuade, sellers must send signals (e.g., 10-year warranties, ISO certificates, expert reviews). Strong signals change receiver perceptions."},
        {"h2_vi":"3. Tại sao nội dung này lại quan trọng cho Marketing hiện đại?","h2_en":"3. Why It Matters for Modern Marketing","content_vi":"Trong kỷ nguyên số, Lòng tin là mặt hàng xa xỉ. Thương hiệu mạnh chính là một hệ thống tín hiệu phức tạp giúp giảm rủi ro cảm nhận của khách hàng. ncsStat giúp bạn đo lường mức độ tác động của các tín hiệu (như CSR, Thương hiệu cá nhân) đến hành vi trung thành.","content_en":"In the digital age, Trust is luxury. Strong branding is a complex signal system reducing perceived risk. ncsStat helps measure signal impacts (like CSR, Personal Branding) on loyalty."},
        {"h2_vi":"4. Cách kiểm định Lý thuyết Tín hiệu trên nền tảng ncsStat","h2_en":"4. Testing Signaling Theory on ncsStat","content_vi":"Bạn có thể sử dụng phương pháp Thực nghiệm hoặc khảo sát bảng hỏi. Với ncsStat, bạn dễ dàng so sánh sự khác biệt giữa các nhóm (T-test, ANOVA) để thấy rõ sức mạnh của việc có và không có tín hiệu ảnh hưởng thế nào đến Ý định mua/tin tưởng.","content_en":"Use experimental designs or surveys. With ncsStat, compare groups (T-test, ANOVA) to see how signals affect purchase intent and trust."}
    ]$$
),
(
    'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80', 
    'cronbach-alpha', 
    'Preliminary Analysis', 
    'Kiểm định Cronbach''s Alpha: Bản giao hưởng của Tin cậy nội tại', 
    'Cronbach''s Alpha Reliability Test: The Symphony of Internal Consistency', 
    'Đừng lạm dụng việc xóa biến bừa bãi chỉ để cố ép Alpha > 0.70. Nếu tập mẫu < 100 hoặc số lượng biến trong một nhân tố chỉ có 2-3 biến, Alpha > 0.60 vẫn được xem là có thể chấp nhận được trong nghiên cứu khám phá.', 
    'Do not indiscriminately delete variables just to force Alpha > 0.70. For exploratory research or small subsets, Alpha > 0.60 is acceptable.', 
    $$[
        {"h2_vi":"1. Nguồn gốc Lịch sử và Triết lý của Cronbach's Alpha","h2_en":"1. Historical Origins and Psychological Philosophy","content_vi":"Lee J. Cronbach giới thiệu hệ số Alpha vào năm 1951, tạo ra một cơn địa chấn trong ngành tâm lý trắc lượng (Psychometrics). Trước thời đại của Cronbach, các nhà khoa học rất chật vật để chứng minh một bài kiểm tra tâm lý là 'đáng tin cậy' (Reliable) mà không bắt đáp viên phải làm lại bài test đó 2 lần (Test-retest reliability). Cronbach's Alpha ra đời dẹp bỏ mọi rào cản đó. Nó là một chỉ số nội tại (Internal Consistency) được đo đạc trong một lần thu thập duy nhất. Hãy tưởng tượng bạn có 5 câu hỏi (items) cùng dùng để đo lường mức độ 'Trầm cảm' của người bệnh. Nếu 5 câu này thực sự phản ánh cùng một bản chất, thì khi bệnh nhân đạt điểm cao ở câu 1, họ bắt buộc phải đạt điểm cao ở câu 2, 3, 4, 5. Sự đồng biến (Covariance) vĩ đại này chính là linh hồn của phương pháp. Nắm được Alpha, bạn nắm được nền tảng vững chắc nhất trước khi bước vào bất kỳ phép phân tích nhân tố nào.","content_en":"Lee J. Cronbach introduced the Alpha coefficient in 1951, sparking a revolution in Psychometrics. Prior to Alpha, verifying test reliability required administering the same test twice (Test-retest reliability). Cronbach's Alpha solved this by determining Internal Consistency from a single administration. Imagine having 5 items measuring 'Depression'. If they truly capture the same construct, high scores on item 1 should mathematically guarantee high scores on the others. This massive Covariance is the absolute soul of the methodology, serving as the bedrock prior to any factor extraction."},
        {"h2_vi":"2. Giải phẫu Công thức Toán học và Bẫy Chiều dài thang đo","h2_en":"2. Mathematical Anatomy and the Scale Length Trap","content_vi":"Về mặt công thức, Cronbach's Alpha phụ thuộc vào 2 biến số cực kỳ nền tảng: Số lượng biến quan sát (K) và Tương quan trung bình (Average inter-item correlation). Một bí mật chết người mà các giáo trình đại học thường giấu đi: 'Bạn càng nhét nhiều câu hỏi vào một nhân tố, hệ số Alpha sẽ CÀNG TĂNG, bất chấp việc các câu hỏi đó có xàm xí đến đâu!'. Đây chính là Bẫy chiều dài thang đo. Nếu bạn có 20 câu hỏi đo lường sự hài lòng, hệ số Alpha chắc chắn sẽ tiệm cận 0.99. Nhưng về mặt học thuật, 20 câu hỏi gây suy kiệt nhận thức cho đáp viên (Respondent fatigue) và làm nảy sinh hiện tượng trùng lặp (Redundancy). Số lượng câu hỏi tối ưu nhất của một nhân tố chỉ nên dao động từ 3 đến 6 câu. Hãy thiết kế thang đo tinh gọn và sâu sắc thay vì một thang đo dài lê thê vô nghĩa.","content_en":"Mathematically, Cronbach's Alpha relies on the number of items (K) and their average inter-item correlation. A lethal secret often omitted in academic texts is that: 'The more items you cram into a construct, the higher the Alpha score goes, regardless of item quality!'. This is the Scale Length Trap. Measuring satisfaction with 20 redundant questions mathematically forces Alpha towards 0.99, but induces massive respondent fatigue and invalidates real discovery. The golden standard limits a construct to strictly 3-6 highly resonant variables."},
        {"h2_vi":"3. Tiêu chuẩn Đánh giá: Ranh giới giữa Vàng và Rác","h2_en":"3. Evaluation Criteria: Border between Gold and Garbage","content_vi":"Nunnally (1978) đã thiết lập bộ tiêu chuẩn vĩ đại sau:\n- Alpha < 0.60: Tính nhất quán kém. Thường xảy ra khi mẫu quá nhỏ hoặc các câu hỏi được dịch sai nghĩa từ tiếng Anh sang tiếng Việt. Bạn bắt buộc phải xem xét xóa bớt các câu không liên quan.\n- 0.60 <= Alpha < 0.70: Có thể chấp nhận được. Mức này CHỈ DÀNH cho các nghiên cứu khám phá tiên phong (Exploratory Research) khi bạn tự sáng tác ra một bộ câu hỏi hoàn toàn mới chưa từng có trên thế giới.\n- 0.70 <= Alpha < 0.80: Tính nhất quán Tốt. Đây là ranh giới an toàn tuyệt đối cho hầu hết mọi luận văn Thạc sĩ và Tiến sĩ.\n- 0.80 <= Alpha < 0.90: Tính nhất quán Tuyệt vời. Chuẩn mực vàng cho các bài báo xuất bản hằng năm trên hệ thống tạp chí Scopus Q1, Q2 hoặc Web of Science.\n- Alpha > 0.95: Điểm chí mạng. Mô hình đang mắc phải căn bệnh 'Đa cộng tuyến nội tại'. Có thể 2 câu hỏi trong bảng của bạn đang lặp lại y chang nhau về mặt từ ngữ, khiến đáp viên lười đọc và đánh bừa cùng một mức điểm.","content_en":"Nunnally's (1978) monumental benchmarks dictate:\n- Alpha < 0.60: Poor. Signifies bad translation or erratic survey design. Interventions are mandatory.\n- 0.60 - 0.70: Acceptable ONLY for groundbreaking exploratory stages evaluating completely newly coined instruments.\n- 0.70 - 0.80: Good. The standard baseline for solid Master's/Ph.D. theses.\n- 0.80 - 0.90: Excellent. The rigid gold standard strictly required by top-tier Scopus Q1/Q2 and WoS indexed journals.\n- Alpha > 0.95: A fatal redundancy indicator. You likely asked the exact same semantic question twice, breaking construct dimensionality."},
        {"h2_vi":"4. Vũ khí Tối thượng: Bẫy Tương quan Biến Tổng (Item-Total Correlation)","h2_en":"4. The Ultimate Weapon: Corrected Item-Total Correlation","content_vi":"Rất nhiều nhà nghiên cứu chỉ thoi thóp theo dõi con số Alpha tổng quát. Thực tế, tại ncsStat và SPSS, cột 'Corrected Item-Total Correlation' mới là Bác sĩ phẫu thuật. Nó đánh giá mức độ gắn kết của MỘT câu hỏi cụ thể so với tổng số điểm của TẤT CẢ các câu hỏi còn lại trong tổ hợp.\nNếu hệ số này < 0.30 (Hoặc cực đoan hơn là mang số âm), điều đó chứng tỏ câu hỏi này đang 'đi ngược chiều' hoặc hoàn toàn rác rưởi so với bản chất của nhóm. Bạn phải DŨNG CẢM LOẠI BỎ (Delete) nó! Khi hệ thống cắt đứt nguồn ung thư này, hãy nhìn qua cột 'Cronbach's Alpha if item deleted', bạn sẽ thấy hệ số Alpha của toàn hệ thống sẽ lập tức vụt sáng và tăng trưởng mạnh mẽ, cứu sống toàn bộ bài nghiên cứu.","content_en":"Many scholars blindly stare at the global Alpha output. However, the 'Corrected Item-Total Correlation' is the real surgical scalpel. It evaluates how strongly a single specific item correlates with the aggregate score of the remaining bundle.\nAccording to Churchill (1979), any item failing to reach the 0.30 threshold is considered malignant garbage, often confusing the respondents. You must courageously DELETE such items! Monitor the 'Cronbach's Alpha if item deleted' metric to witness your overall construct stability resurrect immediately after extracting the malicious variable."},
        {"h2_vi":"5. Lời nguyền Âm: Khi Cronbach's Alpha mang Dấu Trừ (-)","h2_en":"5. The Negative Curse: When Alpha Becomes Negative","content_vi":"Trong quá trình làm data dịch vụ, bạn có bao giờ sốc khi thấy Alpha = -0.521? Đừng hoảng sợ, công thức toán học bị phá vỡ vì sự xuất hiện của 'Câu hỏi Đảo ngược' (Reverse-coded items). Ví dụ: Câu 1: 'Tôi thích mua iPhone' (5 điểm). Câu 2: 'Tôi ghét hệ điều hành iOS' (5 điểm). Nếu đáp viên đánh 5 điểm cho cả 2 câu, sự logic bị gãy vụn tạo ra tương quan âm (Negative correlation) vô cùng lớn. Giải pháp trên hệ thống rất đơn giản: Đảo ngược lại giá trị (Từ 1-5 thành 5-1) cho các biến có cấu trúc phủ định bằng hệ thống Recode (Mã hóa lại) trước khi thả dữ liệu vào module phân tích độ tin cậy.","content_en":"Have you ever been horrified seeing a negative Alpha, like -0.521? Panic not. This statistical singularity occurs when Reverse-coded items accidentally disrupt the unidirectional covariance matrix. E.g., Item 1: 'I love iPhone', Item 2: 'I despise iOS'. If participants lazily rate '5 - Strongly Agree' on both, massive negative covariance tears the algorithm apart. The mandatory fix is initiating an Inverse Recode (flipping 1-5 to 5-1) on negative statements prior to executing scale reliability evaluations."},
        {"h2_vi":"6. Sự nhầm lẫn vĩ đại: Thang đo Phản ánh vs Thang đo Tạo thành","h2_en":"6. The Great Confusion: Reflective vs Formative Scales","content_vi":"Đây là khái niệm hàn lâm phân loại đẳng cấp của các tiến sĩ: Cronbach's Alpha CHỈ CÓ GIÁ TRỊ với 'Thang đo Phản ánh' (Reflective scales) - Nơi mà các biến giống như cái bóng, cùng rọi rọi ra từ một bản thể duy nhất (Ví dụ: Sự tự tin phản ánh ra qua nụ cười, dáng đứng, giọng nói). Các biến này bắt buộc phải có tính 'có thể hoán đổi cho nhau' (Interchangeable).\nTrong khi đó, với 'Thang đo Tạo thành' (Formative scales) - Nơi các biến là NGUYÊN NHÂN cấu tạo nên nhân tố (Ví dụ: Chỉ số kinh tế quốc gia được tạo thành từ Thuế, Xuất khẩu, Tiêu dùng). Rõ ràng Thuế và Xuất khẩu không bắt buộc phải đồng biến với nhau. Nếu bạn dại dột mang Thang đo tạo thành đi chạy Cronbach's Alpha, kết quả sẽ thất bại thảm hại. Hãy cẩn trọng trước khi nhấn nút!","content_en":"This strictly separates amateur researchers from advanced statisticians: Cronbach's Alpha is STRICTLY VALID exclusively for 'Reflective' scales - where causality flows from the latent construct to the explicit indicators (e.g., Confidence reflecting via posture, voice). These interchangeable variables naturally covary.\nConversely, applying Alpha evaluations against 'Formative' variables (where causality flows from diverse distinct pillars to define a construct, e.g., Human Development Index comprising Literacy, Lifespan, and Income) is an academic disaster. Literacy and Lifespan don't systematically inter-correlate. Running Cronbach on Formative models equates to a theoretical suicide."},
        {"h2_vi":"7. Hướng dẫn Phân tích Thực chiến Chuẩn APA 7th trên ncsStat","h2_en":"7. ncsStat Execution Workflow & APA 7th Edition Reporting","content_vi":"Để chinh phục Hội đồng khoa học khó tính nhất, hãy thực thi tuần tự quy trình đo lường tại ncsStat:\nBước 1: Tại Dashboard, chọn 'Kiểm định Độ tin cậy (Cronbach's Alpha)'. Không bao giờ ném toàn bộ các nhân tố vào cùng một rổ. Bạn phải nhặt cẩn thận từng nhóm. Ví dụ, nhặt biến PU1, PU2, PU3, PU4 đưa vào ô Phân Tích.\nBước 2: Hệ thống chạy siêu tốc và trả về khối Matrix. Xem lướt mục 'Corrected Item-Total' > 0.3.\nBước 3: Ghi nhận hệ số Alpha, sử dụng tính năng Export chuẩn APA trực tiếp ra phần mềm Microsoft Word. \nCấu trúc diễn giải luận văn thần thánh: 'Thang đo Sự hữu ích cảm nhận (PU) bao gồm 4 biến quan sát, đạt độ tin cậy tuyệt vời với hệ số Cronbach’s alpha = 0.842. Tương quan biến – tổng của các biến quan sát đều lớn hơn 0.30 (cao nhất là PU3 với 0.741, thấp nhất là PU1 với 0.582), thỏa mãn điều kiện nghiêm ngặt của Hair et al. (2014) về tính nhất quán nội tại.'","content_en":"To mathematically obliterate reviewer critiques, utilize ncsStat's rigid APA paradigm:\nStep 1: Navigate to 'Reliability Test'. Never bulk-insert all questionnaire items. Isolate variables per singular construct (e.g., inject PU1 - PU4 only).\nStep 2: Command the execution. Inspect the generated matrix explicitly targeting 'Corrected Item-Total Correlation' ensuring standard thresholds (> 0.3) are flawlessly met.\nStep 3: Exploit the one-click ncsStat APA Table generator to directly migrate outputs into MS Word without manual cell configuration. \nMagical Reporting Script: 'The construct Perceived Usefulness (PU), measured via 4 robust items, exhibited superb internal consistency (Cronbach’s alpha = 0.842). All corrected item-total correlations robustly exceeded the 0.30 baseline, decisively satisfying psychometric criteria suggested by Hair et al. (2014).'"}
    ]$$
),
(
    'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8011', 
    'efa-factor-analysis', 
    'Factor Analysis', 
    'Phân tích nhân tố khám phá (EFA): Cỗ máy lọc nhiễu dữ liệu vĩ đại', 
    'Exploratory Factor Analysis (EFA): Discovering Inner Structures', 
    'Luôn kiểm tra ma trận xoay (Rotated Component Matrix). Nếu một biến (Ví dụ PU1) có hệ số tải (Factor Loading) lớn hơn 0.5 ở cả HAI CỘT khác nhau, biến đó đang bị tải chéo (Cross-loading) và cực kỳ nguy hiểm, bắt buộc phải loại bỏ.', 
    'Always inspect the Rotated Component Matrix. If an item loads > 0.5 on TWO different components, it is cross-loading and should be deleted to maintain discriminant validity.', 
    $$[
        {"h2_vi":"1. Tại sao phải chạy EFA sau khi chạy Cronbach's Alpha?","h2_en":"1. Why run EFA after Alpha?","content_vi":"Khi chạy Cronbach's Alpha, bạn đang NHỒI ÉP máy tính tin rằng 5 biến PU1-PU5 thuộc về nhau. Nhưng điều này mang tính chủ quan. Đôi khi thiết kế bảng hỏi rất đẹp, nhưng đáp viên lúc điền lại hiểu lầm câu PU5 giống với câu PEOU2. Phân tích EFA (Exploratory Factor Analysis) giống như một cái máy rây bột. Cứ ném 30 câu hỏi của bạn vào, EFA sẽ tự động nhóm các câu hỏi có cùng tính chất về với nhau một cách khách quan nhất! Nếu PU5 bị đáp viên hiểu nhầm, EFA sẽ bế ngay PU5 sang bên nhóm PEOU. Lúc này bạn sẽ phát hiện sai sót của bảng hỏi.","content_en":"Alpha assumes items belong together (subjective). EFA acts as a sieve, objectively grouping items based solely on data responses. If respondents confused PU5 with PEOU2, EFA will mathematically rip PU5 out of the PU group and dump it into PEOU, revealing design flaws."},
        {"h2_vi":"2. Tiêu chuẩn KMO và Bartlett's Test: Tấm vé qua cửa","h2_en":"2. KMO and Bartlett's Test: The Ticket In","content_vi":"Trước khi đọc bảng kết quả xoay, Hội đồng bảo vệ luôn nhìn vào Bảng đầu tiên:\n- KMO (Kaiser-Meyer-Olkin): Hệ số này phải từ 0.5 đến 1. Nếu KMO < 0.5, vô phương cứu chữa, tập dữ liệu của bạn không phù hợp để phân tích nhân tố (Biến quá rời rạc, mẫu quá nhỏ).\n- Kiểm định Bartlett: Mức ý nghĩa Sig. (p-value) phải < 0.05. Nó chứng minh các biến có sự tương quan với nhau trong tổng thể đại đám. Đạt 2 điều kiện này, bạn mới có tư cách đọc tiếp các bảng bên dưới!","content_en":"Before looking at the clusters, check: 1. KMO index must be >= 0.5 (measures sampling adequacy). 2. Bartlett's Test of Sphericity Sig (p-value) must be < 0.05, proving correlation matrix is not an identity matrix."},
        {"h2_vi":"3. Total Variance Explained và Eigenvalues","h2_en":"3. Eigenvalues and Variance Explained","content_vi":"- Eigenvalue > 1: Là chuẩn Kaiser. Máy tính sẽ chỉ giữ lại những nhân tố nào có độ tinh lọc Eigenvalue vĩ đại hơn 1.\n- Total Variance Explained (Phương sai trích): Phải >= 50% (hoặc chặt chẽ hơn là >= 60%). Điều này có nghĩa là các nhân tố mà bạn rút ra sau cùng đại diện và giải thích được ít nhất là 50% sự biến thiên của toàn bộ tập dữ liệu thô ban đầu. Nếu nhỏ hơn 50%, mô hình của bạn đang giải thích thực tế rất yếu ớt.","content_en":"- Eigenvalue > 1 (Kaiser Criterion): Only components with Eigenvalues > 1 are extracted.\n- Total Variance Explained: Must be >= 50% (or ideally 60%+). If lower, the extracted factors fail to adequately represent the original data's variability."},
        {"h2_vi":"4. Pattern Matrix & Bí kíp xử lý tải chéo (Cross-loading)","h2_en":"4. Rotated Matrix & Cross-loadings","content_vi":"Ma trận xoay (Rotated Component Matrix) là linh hồn của EFA. Khuyến nghị chuẩn với các bài báo ISI:\n- Factor Loading (Hệ số tải) của từng biến lên nhân tố mẹ phải từ 0.50 trở lên.\n- Hiện tượng Tải chéo (Cross-loading): Khi biến PU1 vừa có hệ số tải 0.65 ở Cột 1, lại vừa có hệ số tải 0.55 ở Cột 3. Chênh lệch giữa 2 hệ số này < 0.3. ĐÂY LÀ ĐIỀU TỐI KỴ! Nghĩa là PU1 đang bị lưỡng tính, đáp viên không phân biệt được biến này đang hỏi về chủ đề gì. Với ncsStat, khi nhận diện có tải chéo, bạn nên chạy lại EFA nhưng gỡ biến đó ra khỏi hộp Input.","content_en":"The Rotated Matrix is the soul of EFA. Items must load strongly (>= 0.50) on their primary factor. Beware of Cross-loading: An item loading heavily on two columns without a clear gap (> 0.2/0.3). Cross-loaded variables destroy discriminant validity and must be systematically removed."}
    ]$$
),
(
    'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f801122', 
    'regression-vif-multicollinearity', 
    'Impact Analysis', 
    'Hồi quy tuyến tính Đa biến và rào cản Đa cộng tuyến (VIF)', 
    'Multiple Regression & VIF: Predicting the Future', 
    'Tuyệt đối không đưa các biến độc lập có hệ số tương quan (Pearson) > 0.8 vào cùng một mô hình hồi quy. Chúng sẽ dẫm đạp lên nhau sinh ra hiện tượng Đa cộng tuyến, làm sai lệch toàn bộ hệ số Beta.', 
    'Never insert independent variables with a Pearson correlation > 0.8 into the same regression block. They will cannibalize each other, causing extreme Multicollinearity and twisting your Beta outcomes.', 
    $$[
        {"h2_vi":"1. Tại sao Hồi quy lại là Vua của Phân tích Thống kê?","h2_en":"1. Why Regression is the King of Statistics","content_vi":"Bạn có tập dữ liệu gồm Mức lương, Môi trường làm việc và Căng thẳng (Độc lập X). Bạn muốn biết yếu tố nào tác động mạnh nhất đến Quyết định nghỉ việc (Phụ thuộc Y) của nhân viên. Nắm được Hồi quy Đa biến (Multiple Linear Regression) chính là chìa khóa để kiến tạo nên nghệ thuật Dự báo. Hồi quy không dừng ở việc so sánh (như T-Test), mà tính chính xác các trọng số tác động: 'Nếu Môi trường làm việc tăng thêm 1 điểm, tỷ lệ nghỉ việc giảm đi bao nhiêu phần trăm?'.","content_en":"If you want to know which factors (like Salary, Stress) impact Turnover Intention (Dependent Y) the most, Multiple Regression is your crystal ball. It doesn't just compare; it produces exact predictive weights."},
        {"h2_vi":"2. R-Square: Năng lực giải thích của mô hình","h2_en":"2. R-Square: Predictive Power","content_vi":"Khi bạn phân tích kết quả Hồi quy trên ncsStat, chỉ số đầu tiên phải xem là R-Square (R Bình phương) hoặc Adjusted R-Square (R Bình phương hiệu chỉnh). Nếu R-Square = 0.65, hãy tự hào vì mô hình 3 biến độc lập của bạn đã Giải thích được tới 65% sự biến thiên của Quyết định nghỉ việc. 35% còn lại nằm ở các yếu tố mà bạn chưa điều tra (Vd: Sức khỏe, Hoàn cảnh gia đình...). Trong khoa học hành vi xã hội, R-square > 0.4 đã là một kết quả tuyệt vời.","content_en":"Look at Adjusted R-Square first. If R-Square = 0.65, your independent variables successfully explain 65% of the variance in the dependent variable. In social sciences, an R-Square > 0.4 is generally considered excellent."},
        {"h2_vi":"3. Đa cộng tuyến & Bóng mây Hệ số VIF (Variance Inflation Factor)","h2_en":"3. Multicollinearity & the VIF Shadow","content_vi":"Đây là nỗi ác mộng của mọi luận văn. Đa cộng tuyến xảy ra khi có 2 biến độc lập lại bị 'tương quan' mạnh với nhau (Ví dụ bạn đưa cả biến 'Lương Net' và 'Lương Gross' vào cùng 1 PT). Chúng sẽ chém giết lẫn nhau làm hệ số Beta âm đi một cách vô lý.\nTrọng tài phân xử chính là Hệ số phóng đại phương sai (VIF - Variance Inflation Factor):\n- VIF < 2 (hoặc < 3): Dữ liệu cực an toàn, không có bóng dáng đa cộng tuyến.\n- VIF trong khoảng 3 - 5: Có hiện tượng đa cộng tuyến nhẹ, cần lưu ý.\n- VIF > 10: Mô hình bị sụp đổ toàn diện. Hãy lập tức gỡ bỏ biến độc lập nào đang có VIF > 10 ra khỏi mô hình và chạy lại.","content_en":"Multicollinearity is a fatal disease where independent variables are too highly correlated. It destroys Beta estimates. Evaluate the Variance Inflation Factor (VIF). VIF < 3 is perfect. VIF > 5 is dangerous. VIF > 10 means your model collapses completely. Remove the offending variables immediately."},
        {"h2_vi":"4. Quyết định Vận mệnh: Độ tin cậy (P-value) & Trọng lượng (Beta)","h2_en":"4. Fate Decision: P-value Sig & Beta Weights","content_vi":"- Chỉ số Sig (p-value): Giống như tiếng búa của quan tòa. Nếu Sig. > 0.05, phán quyết là: Nhân tố đó KHÔNG HỀ TÁC ĐỘNG đến ý định nghỉ việc. Chấm hết. Bảng số liệu Beta của nó vô giá trị.\n- Hệ số Beta Chuẩn hóa (Standardized Beta): Đối với các nhân tố đã pass qua vòng Sig. < 0.05, hãy đọ xem Beta của thằng nào lớn hơn. Biến nào có Beta Chuẩn hóa VỀ ĐỘ LỚN TUYỆT ĐỐI lớn nhất, biến đó là Kẻ chi phối mạnh nhất. Lúc này trong báo cáo, bạn có thể tự tin đề xuất Doanh nghiệp nên ưu tiên cải thiện biến này đầu tiên với nguồn ngân sách hạn hẹp.","content_en":"- Sig (p-value): The judge's gavel. If Sig > 0.05, the variable has NO statutory impact. Stop interpreting it.\n- Standardized Beta: For variables with Sig < 0.05, compare their absolute Standardized Beta. The largest Beta indicates the strongest impact factor, guiding policymakers on where to focus budget interventions."}
    ]$$
)
ON CONFLICT (slug) DO UPDATE SET 
    title_vi = EXCLUDED.title_vi,
    title_en = EXCLUDED.title_en,
    expert_tip_vi = EXCLUDED.expert_tip_vi,
    expert_tip_en = EXCLUDED.expert_tip_en,
    content_structure = EXCLUDED.content_structure;
