-- =========================================================================
-- NCSKIT 2026 - LONG-FORM EXPERT ARTICLES (FIXED JSON SYNTAX)
-- Use Dollar-Quoting ($$ ... $$) for safe SQL insertion
-- =========================================================================

INSERT INTO "public"."knowledge_articles" ("id", "slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") VALUES 
(
    'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 
    'technology-acceptance-model-tam', 
    'Research Models', 
    'Mô hình Chấp nhận Công nghệ (TAM): Hướng dẫn Chuyên sâu và Kịch bản chạy Data (Toàn tập)', 
    'Technology Acceptance Model (TAM): The Ultimate Guide', 
    'Đừng chỉ dừng lại ở mô hình gốc năm 1989. Để bài báo đạt chuẩn Scopus/ISI, bạn nên tích hợp TAM với các yếu tố như Trust (Niềm tin), Perceived Risk (Rủi ro cảm nhận) hoặc Mobility (Tính di động) để tạo ra sự đóng góp mới (Novelty).', 
    'Move beyond the 1989 original. For Scopus/ISI standards, integrate TAM with Trust, Perceived Risk, or context-specific factors like Mobility.', 
    $$[
        {"h2_vi":"1. Tổng quan vĩ mô về TAM và Nguồn gốc Kỷ nguyên Số (1000+ words scope)","h2_en":"1. Macro Overview of TAM and Digital Era Origins","content_vi":"Mô hình Chấp nhận Công nghệ (Technology Acceptance Model - TAM) do Tiến sĩ Fred Davis tiên phong đề xuất vào năm 1989 tại MIT. Hiện tại, TAM được coi là 'kim chỉ nam' vĩ đại nhất trong các nghiên cứu về chuỗi hành vi sử dụng Công Nghệ Thông Tin (IT) Hệ thống quản trị (MIS), công nghệ di động và kinh tế số. Được xây dựng dựa trên nền tảng của Thuyết Hành động Hợp lý (Theory of Reasoned Action - TRA) của Fishbein và Ajzen, TAM tối giản hóa các ràng buộc phức tạp của tâm lý học hành vi con người thành hai yếu tố tiên quyết rõ ràng minh bạch nhất: Sự hữu ích cảm nhận được (Perceived Usefulness - PU) và Tương tác dễ dàng cảm nhận được (Perceived Ease of Use - PEOU). Trong hơn 3 thập kỷ, TAM đã được kiểm chứng trên hàng triệu tập khách hàng, từ việc sinh viên dùng E-learning, khách hàng dùng Mobile Banking, cho đến nhân viên văn phòng chuyển đổi sang AI và ChatGPT. Sức sống của TAM nằm ở sự đơn giản, tính tùy biến cực cao, cho phép các tiến sĩ, thạc sĩ dễ dàng 'cấy ghép' thêm vô số các biến ngoại lai (External Variables) để đo lường bối cảnh cụ thể của tổ chức.","content_en":"The Technology Acceptance Model (TAM) was proposed by Fred Davis in 1989. Over 30 years later, it remains the 'common language' for seekers in MIS and Business Management wanting to understand tech adoption."},
        {"h2_vi":"2. Giải phẫu cấu trúc Lõi: PU và PEOU","h2_en":"2. Anatomical Structure: PU and PEOU","content_vi":"Cấu trúc lõi của TAM luôn đảm bảo tính bền vững của các mối quan hệ (Structural Links):\n- Sự hữu ích cảm nhận (PU - Perceived Usefulness): Được định nghĩa là mức độ mà một cá nhân tin rằng, bằng cách sử dụng một hệ thống cụ thể, hiệu suất công việc hay cuộc sống của họ sẽ được tự động nâng cao rõ rệt. PU phản ánh tính thực tế (Pragmatic Value). Nếu một App đẹp nhưng không giải quyết được vấn đề thực tiễn, PU sẽ tụt thảm hại, kéo theo sự diệt vong của sản phẩm.\n- Sự dễ sử dụng cảm nhận (PEOU - Perceived Ease of Use): Là mức độ mà người dùng tin rằng việc tiếp xúc và làm chủ công nghệ mới hầu như không đòi hỏi quá nhiều hao tổn về chất xám hay sức lực (Free of effort). \n- Mối quan hệ tương hỗ: Trong hệ thống TAM, PEOU đóng vai trò như một đòn bẩy kép. Nó không chỉ tác động trực tiếp đến Thái độ (Attitude) và Ý định hành vi (BI), mà còn có tác động dương(+) trực tiếp lên chính PU. Nói cách khác: 'Cái gì càng dễ dùng, người ta càng nhanh chóng nhận ra sự hữu ích của nó'.","content_en":"- Perceived Usefulness (PU): The degree to which a user believes tech improves performance.\n- Perceived Ease of Use (PEOU): The degree to which a user believes tech requires minimal effort. PEOU often impacts PU: ease leads to usefulness."},
        {"h2_vi":"3. Sự tiến hóa: TAM2, TAM3 và Kỷ nguyên UTAUT","h2_en":"3. Evolution: TAM2, TAM3, and UTAUT","content_vi":"Khoa học không bao giờ đứng yên. Dù TAM rất tuyệt vời, nhưng Davis đã nhận ra rằng PU và PEOU chưa đủ để giải thích hoàn toàn Ý định trong môi trường làm việc ép buộc. Do đó:\n- TAM2 (Venkatesh & Davis, 2000): Bổ sung thêm các yếu tố Xã hội học (Social Influence Variables) bảo gồm Chuẩn chủ quan (Subjective Norm), Hình ảnh cá nhân (Image), Tính tự nguyện (Voluntariness), cùng các yếu tố thuộc về Hệ thống như Đặc tính công việc (Job Relevance) và Mức độ tương thích (Output Quality).\n- TAM3 (Venkatesh & Bala, 2008): Lại là một bước nhảy vọt khi tập trung giải phẫu 100% vào nguồn gốc của PEOU. Nó chứng minh rằng Trải nghiệm quá khứ (Computer Playfulness), Tính tự tôn thiết bị (Computer Self-efficacy) và Lo âu công nghệ (Computer Anxiety) đóng vai trò điều hướng người dùng.\n- Đỉnh cao UTAUT (2003): Là sự tổng hòa vĩ đại của 8 hệ thống lý thuyết (TRA, TAM, TPB...). UTAUT cho ra đời 4 trụ cột: Hiệu quả kỳ vọng (Performance Expectancy), Nỗ lực kỳ vọng (Effort Expectancy), Ảnh hưởng xã hội (Social Influence) và Điều kiện thuận lợi (Facilitating Conditions), giúp cho hiệu suất dự phân (Khả năng giải thích phương sai R-square) đạt ngưỡng khổng lồ (lên tới 70% so với 40% của nguyên bản TAM).","content_en":"TAM evolved into TAM2 (adding social factors like Subjective Norms) and TAM3 (focusing on PEOU determinants). Finally, UTAUT (2003) integrated 8 theories, achieving 70% predictive accuracy."},
        {"h2_vi":"4. Các kịch bản mở rộng (Extensions) nâng chuẩn Scopus / ISI","h2_en":"4. Extensions for Scopus / ISI Standards","content_vi":"Để bài luận văn, Luận án Tiến sĩ hoặc bài báo ISI của bạn được Reviewer (người phản biện) đánh giá cao về tính mới (Novelty), tuyệt đối không được bê nguyên xi mô hình cũ. Hãy 'độ' thêm các biến số sao cho phù hợp với thời đại 4.0:\n- Tích hợp 'Trust' (Niềm tin) & 'Perceived Risk' (Rủi ro cảm nhận): Khi bạn nghiên cứu về FinTech, Ví điện tử hay Thương mại điện tử, Rủi ro tài chính, Rủi ro bảo mật là cực kỳ hiện hữu. Hãy biến Trust thành Biến trung gian (Mediator) hoặc Rủi ro thành biến cản trở (Negative independent variable).\n- Tích hợp Kích thích - Phản ứng (S-O-R Model): Bạn có thể cho phép Giao diện App (Visual Design), Mức độ cá nhân hóa (Personalization) làm biến kích thích đầu vào (Stimuli), tác động tới PU/PEOU (Organism) dẫn đến sự hình thành Hành động Mua hàng (Response).\n- Biến Điều Tiết (Moderators): Sự kỳ diệu của thống kê nằm ở việc phát hiện ra rằng 'Tính cách khác nhau sẽ dẫn đến sự lựa chọn khác nhau'. Trên nền tảng ncsStat, hãy sử dụng Phân tích Đa nhóm (Multi-group Analysis / ANOVA) để kiểm tra xem Giới tính (Nam/Nữ) hay Độ tuổi (Gen Z vs Gen X) sẽ làm thay đổi độ mạnh yếu của đường dẫn từ PU -> BI hay không. Người trẻ thường quan tâm PEOU, trong khi người lớn tuổi quan tâm PU và Rủi ro.","content_en":"Integrate TAM with Trust for Fintech, use SOR models for e-commerce, and utilize Demographic Moderators (Age, Gender) to uncover deeper narrative insights and secure high Scopus journal acceptances."},
        {"h2_vi":"5. Lộ trình Phân tích Dữ liệu TAM chuẩn APA Thực Chiến với ncsStat","h2_en":"5. Practical Data Analysis Workflow on ncsStat","content_vi":"Để minh chứng mô hình TAM có ý nghĩa thống kê trên thực tế tại thị trường Việt Nam, hãy làm theo quy trình tinh gọn 4 bước trên hệ thống máy chủ ncsStat:\n\nBƯỚC 1: LÀM SẠCH VÀ MÔ TẢ (Descriptive Statistics)\n- Lọc Outliers ra khỏi dữ liệu thô. Chạy Tần số để trình bày Demographic của mẫu (VD: 60% nữ, 40% nam). Điều này giúp Reviewer thấy được sự minh bạch của dữ liệu thu thập.\n\nBƯỚC 2: CỦNG CỐ CÔNG CỤ ĐO LƯỜNG (Reliability & Factor Analysis)\n- Cronbach's Alpha: Chạy Alpha cho PU, PEOU, BI. Yêu cầu Alpha > 0.70. Nếu biến PU3 làm giảm độ tin cậy Alpha (Nhìn vào cột Item-Total Correlation < 0.3), hãy thẳng tay loại bỏ biến đó ngay trong lần đo đầu tiên.\n- EFA (Exploratory Factor Analysis): Tách cấu trúc nhân tố. Sử dụng phương pháp trích xuất Principal Component, phép xoay Promax hoặc Varimax. Hệ số KMO phải >= 0.5; Bartlett Test phải mang ý nghĩa (p < 0.05). Factor Loadings của biến quan sát (VD: PU1) phải tựu trung mượt mà trên cùng một cột và chỉ số tải > 0.5.\n\nBƯỚC 3: KIỂM ĐỊNH MÔ HÌNH CẤU TRÚC (Regression Analysis)\n- Vào tab Regression, đưa Ý định (BI) vào mục Dependent, và PU, PEOU vào Independent. Xem xét chỉ số VIF, nếu VIF < 3 là cấu trúc dữ liệu cực kỳ tuyệt vời (không có đa cộng tuyến).\n- Đọc hệ số Beta (Standardized Beta): Giá trị Beta càng cao, mũi tên tác động trong hình vẽ (Path diagram) càng đậm. Xác nhận xem P-value (Sig) có < 0.05 để bác bỏ giả thuyết Không (H0) và chấp nhận Giả thuyết Nghiên cứu (H1) hay không.\n\nBƯỚC 4: BÁO CÁO KẾT QUẢ THEO APA 7TH EDITION\n- ncsStat hỗ trợ kết xuất (Export) thẳng các bảng biểu Thống kê định dạng theo chuẩn APA toàn cầu. Dán trực tiếp bảng này vào Microsoft Word mà không cần tự kẻ bảng rườm rà. Chú ý luôn viết In nghiêng các trị số t, p, F. Ví dụ: 'Sự hữu ích cảm nhận (PU) đã tác động thuận chiều mạnh nhất tới Ý định sử dụng thiết bị AI (β = 0.45, t = 6.82, p < 0.001)'.","content_en":"Run a robust workflow on ncsStat: 1. Clean Data & Outliers; 2. Cronbach Alpha & EFA Extrapolations (ensuring Validity); 3. Regression Analysis (monitoring VIF and P-Values < 0.05); 4. Report via one-click APA compliant table generation directly into Word."}
    ]$$
),
(
    'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e', 
    'theory-of-planned-behavior-tpb', 
    'Behavioral Research', 
    'Thuyết Hành vi Dự định (TPB): Chìa khóa vàng giải mã Ý định',
    'Theory of Planned Behavior (TPB): The Golden Key to Intention', 
    'Hãy chú ý đến khoảng cách giữa Ý định (Intention) và Hành vi thực tế (Behavior). Nhiều nghiên cứu cho thấy Ý định rất cao nhưng Hành vi lại thấp. Đừng quên đưa biến PBC vào như một biến điều tiết.', 
    'Pay attention to the Intention-Behavior gap. Use Perceived Behavioral Control (PBC) as a moderator to deepen your analysis.', 
    $$[
        {"h2_vi":"1. Từ TRA đến TPB: Bước ngoặt của Icek Ajzen","h2_en":"1. From TRA to TPB: Icek Ajzen's Turning Point","content_vi":"Ban đầu, Thuyết Hành động Hợp lý (TRA) chỉ tập trung vào Thái độ và Chuẩn chủ quan. Tuy nhiên, Ajzen nhận ra rằng con người không luôn có quyền kiểm soát hoàn toàn hành vi của mình (Vd: muốn mua iPhone nhưng không đủ tiền). Do đó, ông đã thêm biến PBC vào năm 1991 để tạo ra TPB.","content_en":"Initially, TRA focused on Attitude and Subjective Norms. Ajzen realized humans lack total control over behaviors (e.g., wanting an iPhone but lacking funds), so he added Perceived Behavioral Control (PBC) in 1991."},
        {"h2_vi":"2. Ba chân kiềng của Ý định hành vi","h2_en":"2. The Three Components of Intention","content_vi":"- Thái độ (Attitude): Đánh giá tích cực hay tiêu cực về hành vi.\n- Chuẩn chủ quan (Subjective Norm): Áp lực từ những người xung quanh (gia đình, bạn bè, đồng nghiệp).\n- Kiểm soát hành vi cảm nhận (PBC): Niềm tin vào khả năng thực hiện hành vi của bản thân mình.","content_en":"- Attitude: Positive or negative evaluation.\n- Subjective Norm: Pressure from social circles.\n- PBC: Self-belief in the ability to perform the behavior."},
        {"h2_vi":"3. Ứng dụng trong Marketing và Tâm lý học","h2_en":"3. Applications in Marketing and Psychology","content_vi":"TPB được dùng để giải thích hầu hết mọi hành vi: Từ việc khách hàng chọn mua thực phẩm hữu cơ, sinh viên quyết định khởi nghiệp, đến cả việc người dân tuân thủ quy định đeo khẩu trang. Trong phân tích trên ncsStat, TPB thường được sử dụng như một khung lý thuyết nền vững chắc.","content_en":"TPB explains diverse behaviors: Buying organic food, student entrepreneurship, or compliance with health regulations. ncsStat users often use TPB as a robust framework."},
        {"h2_vi":"4. Phân tích Mediation (Biến trung gian) trong TPB","h2_en":"4. Mediation Analysis in TPB","content_vi":"Một xu hướng hiện đại là nghiên cứu cách các biến nhân khẩu học hoặc các yếu tố ngoại vi tác động đến Ý định THÔNG QUA ba nhân tố của TPB. ncsStat hỗ trợ bạn chạy kiểm định Sobel hoặc Bootstrapping để xác định chính xác hiệu ứng trung gian này.","content_en":"A modern trend is researching how external factors impact Intention VIA TPB components. ncsStat supports Sobel and Bootstrapping tests to identify these mediation effects."}
    ]$$
),
(
    'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', 
    'signaling-theory-research', 
    'Market Strategy', 
    'Lý thuyết Tín hiệu (Signaling Theory): Khi Hành động thay cho lời nói', 
    'Signaling Theory: Actions Speak Louder Than Words', 
    'Khi làm về Signaling, hãy phân rõ ai là Người phát tín hiệu (Sender) và ai là Người nhận (Receiver). Một tín hiệu không có chi phí (free signal) thường bị coi là cheap talk và không có giá trị.', 
    'Clarify the Sender and Receiver. A free signal is often dismissed as cheap talk and holds no value for investors or search engines.', 
    $$[
        {"h2_vi":"1. Michael Spence và Giải Nobel Kinh tế","h2_en":"1. Michael Spence and the Nobel Prize","content_vi":"Signaling Theory ra đời từ nghiên cứu về thị trường lao động của Michael Spence (1973). Tại sao bằng cấp lại quan trọng ngay cả khi kiến thức trong trường không dùng tới? Vì tấm bằng là một tín hiệu cực kỳ tốn kém về thời gian và trí tuệ, báo hiệu cho nhà tuyển dụng rằng ứng viên là người có năng lực.","content_en":"Born from Michael Spence's 1973 labor market research. Degrees matter because they are a costly signal of time and intelligence, signaling competence to employers."},
        {"h2_vi":"2. Cơ chế hoạt động: Sender - Signal - Receiver","h2_en":"2. Mechanism: Sender - Signal - Receiver","content_vi":"Trong thị trường bất đối xứng thông tin, người bán biết rõ chất lượng sản phẩm hơn người mua. Để thuyết phục, người bán phải phát đi các tín hiệu (Vd: Bảo hành 10 năm, chứng chỉ chất lượng ISO, hoặc đánh giá 5 sao từ chuyên gia). Nếu tín hiệu đủ mạnh, người nhận (Receiver) sẽ thay đổi nhận thức.","content_en":"In asymmetric markets, sellers know quality better than buyers. To persuade, sellers must send signals (e.g., 10-year warranties, ISO certificates, expert reviews). Strong signals change receiver perceptions."},
        {"h2_vi":"3. Tại sao nội dung này lại quan trọng cho Marketing hiện đại?","h2_en":"3. Why It Matters for Modern Marketing","content_vi":"Trong kỷ nguyên số, Lòng tin là mặt hàng xa xỉ. Thương hiệu mạnh chính là một hệ thống tín hiệu phức tạp giúp giảm rủi ro cảm nhận của khách hàng. ncsStat giúp bạn đo lường mức độ tác động của các tín hiệu (như CSR, Thương hiệu cá nhân) đến hành vi trung thành.","content_en":"In the digital age, Trust is luxury. Strong branding is a complex signal system reducing perceived risk. ncsStat helps measure signal impacts (like CSR, Personal Branding) on loyalty."},
        {"h2_vi":"4. Cách kiểm định Lý thuyết Tín hiệu trên nền tảng ncsStat","h2_en":"4. Testing Signaling Theory on ncsStat","content_vi":"Bạn có thể sử dụng phương pháp Thực nghiệm hoặc khảo sát bảng hỏi. Với ncsStat, bạn dễ dàng so sánh sự khác biệt giữa các nhóm (T-test, ANOVA) để thấy rõ sức mạnh của việc có và không có tín hiệu ảnh hưởng thế nào đến Ý định mua/tin tưởng.","content_en":"Use experimental designs or surveys. With ncsStat, compare groups (T-test, ANOVA) to see how signals affect purchase intent and trust."}
    ]$$
)
ON CONFLICT (slug) DO UPDATE SET 
    title_vi = EXCLUDED.title_vi,
    title_en = EXCLUDED.title_en,
    expert_tip_vi = EXCLUDED.expert_tip_vi,
    expert_tip_en = EXCLUDED.expert_tip_en,
    content_structure = EXCLUDED.content_structure;
