export const DEFAULT_R_SCRIPTS: Record<string, string> = {
  "descriptive": "library(psych);\n    df <- as.data.frame({{data}});\n    colnames(df) <- paste0(\"V\", 1:ncol(df));\n    desc <- describe(df, fast=FALSE);\n    list(\n        mean = as.numeric(desc$mean),\n        sd = as.numeric(desc$sd),\n        min = as.numeric(desc$min),\n        max = as.numeric(desc$max),\n        median = as.numeric(desc$median),\n        n = as.numeric(desc$n),\n        skew = as.numeric(desc$skew),\n        kurtosis = as.numeric(desc$kurtosis),\n        se = as.numeric(desc$se)\n    );",
  "correlation": "library(psych);\n    data_mat <- {{data}};\n    df <- as.data.frame(data_mat);\n    colnames(df) <- paste0(\"V\", 1:ncol(df));\n    method_name <- \"{{method}}\";\n    ct <- corr.test(df, use = \"pairwise\", method = method_name, adjust = \"none\");\n    list(\n        correlation = as.vector(ct$r),\n        p_values = as.vector(ct$p),\n        n_cols = ncol(df),\n        n_obs = nrow(df),\n        method = method_name\n    );",
  "ttest-indep": "g1 <- c({{group1}});\n    g2 <- c({{group2}});\n    shapiro_p1 <- tryCatch({ if (length(g1) >= 3) shapiro.test(g1)$p.value else NA }, error = function(e) { NA });\n    shapiro_p2 <- tryCatch({ if (length(g2) >= 3) shapiro.test(g2)$p.value else NA }, error = function(e) { NA });\n    med1 <- median(g1); med2 <- median(g2);\n    z1 <- abs(g1 - med1); z2 <- abs(g2 - med2);\n    levene_res <- tryCatch({\n        combined <- c(z1, z2);\n        group_fact <- factor(c(rep(\"G1\", length(z1)), rep(\"G2\", length(z2))));\n        summary(aov(combined ~ group_fact))[[1]]\n    }, error = function(e) { NULL });\n    lev_p <- if(!is.null(levene_res)) levene_res[\"group_fact\", \"Pr(>F)\"] else 0.5;\n    lev_f <- if(!is.null(levene_res)) levene_res[\"group_fact\", \"F value\"] else 0;\n    var_equal <- lev_p > 0.05;\n    tt <- t.test(g1, g2, var.equal = var_equal);\n    m1 <- mean(g1); m2 <- mean(g2);\n    s1 <- sd(g1); s2 <- sd(g2);\n    n1 <- length(g1); n2 <- length(g2);\n    pooled_sd <- sqrt(((n1-1)*s1^2 + (n2-1)*s2^2)/(n1+n2-2));\n    d <- if(pooled_sd > 0) (m1 - m2) / pooled_sd else 0;\n    list(\n        t = tt$statistic,\n        df = tt$parameter,\n        p_value = tt$p.value,\n        mean1 = m1,\n        mean2 = m2,\n        mean_diff = m1 - m2,\n        ci_lower = tt$conf.int[1],\n        ci_upper = tt$conf.int[2],\n        effect_size = d,\n        levene_p = lev_p,\n        levene_f = lev_f,\n        shapiro_p1 = shapiro_p1,\n        shapiro_p2 = shapiro_p2\n    );",
  "ttest-paired": "b <- c({{before}});\n    a <- c({{after}});\n    diffs <- b - a;\n    sh_p <- tryCatch({ if (length(diffs) >= 3) shapiro.test(diffs)$p.value else NA }, error = function(e) { NA });\n    tt <- t.test(b, a, paired = TRUE);\n    m_diff <- mean(diffs);\n    sd_diff <- sd(diffs);\n    d <- if(!is.na(sd_diff) && sd_diff > 0) m_diff / sd_diff else 0;\n    list(\n        t = tt$statistic,\n        df = tt$parameter,\n        pValue = tt$p.value,\n        meanBefore = mean(b),\n        meanAfter = mean(a),\n        meanDiff = m_diff,\n        ci_lower = tt$conf.int[1],\n        ci_upper = tt$conf.int[2],\n        effect_size = d,\n        norm_p = sh_p\n    );",
  "mann-whitney": "library(psych);\n    g1 <- c({{g1}}); g2 <- c({{g2}});\n    tt <- wilcox.test(g1, g2, conf.int = TRUE);\n    z <- qnorm(tt$p.value / 2, lower.tail = FALSE);\n    r <- z / sqrt(length(g1) + length(g2));\n    sk1 <- skew(g1); sk2 <- skew(g2);\n    sim <- (sign(sk1) == sign(sk2)) && (abs(sk1 - sk2) < 1.0);\n    msg <- if(sim) \"Trung vị\" else \"Mean Rank\";\n    list(stat = tt$statistic, p = tt$p.value, m1 = median(g1), m2 = median(g2), r = r, sk1 = sk1, sk2 = sk2, msg = msg);",
  "chi-square": "v <- c(${flatStr});\n    m <- matrix(v, nrow = ${data.length}, byrow = TRUE);\n    tbl <- table(m[,1], m[,2]);\n    tt <- chisq.test(tbl);\n    n <- sum(tbl);\n    cv <- if(min(dim(tbl)) > 1) sqrt(tt$statistic / (n * (min(dim(tbl)) - 1))) else 0;\n    phi <- NA; fisher_p <- NA; or <- NA;\n    if (nrow(tbl) == 2 && ncol(tbl) == 2) {\n        phi <- sqrt(tt$statistic / n);\n        ft <- fisher.test(tbl);\n        fisher_p <- ft$p.value; or <- ft$estimate;\n    }\n    list(\n        stat = tt$statistic, df = tt$parameter[1], p = tt$p.value,\n        obs = as.matrix(tt$observed), exp = as.matrix(tt$expected),\n        cv = cv, phi = phi, fisher = fisher_p, or = or,\n        rows = rownames(tbl), cols = colnames(tbl),\n        nr = nrow(tbl), nc = ncol(tbl),\n        ovs = as.vector(tt$observed), evs = as.vector(tt$expected)\n    );",
  "kruskal": "vals <- c({{v}}); grps <- factor(c({{g}}));\n    tt <- kruskal.test(vals ~ grps);\n    meds <- as.numeric(tapply(vals, grps, median));\n    pw <- tryCatch({\n        pmat <- pairwise.wilcox.test(vals, grps, p.adjust.method = \"bonferroni\")$p.value;\n        comps <- c(); ps <- c();\n        for(i in 1:nrow(pmat)) for(j in 1:ncol(pmat)) if(!is.na(pmat[i,j])) {\n            comps <- c(comps, paste0(rownames(pmat)[i], \"-\", colnames(pmat)[j]));\n            ps <- c(ps, pmat[i,j]);\n        }\n        list(c = comps, p = ps);\n    }, error = function(e) list(c = c(), p = c()));\n    list(stat = tt$statistic, df = tt$parameter, p = tt$p.value, meds = meds, m = tt$method, ph_c = pw$c, ph_p = pw$p);",
  "wilcoxon": "b <- c({{b}}); a <- c({{a}});\n    tt <- wilcox.test(b, a, paired = TRUE, conf.int = TRUE);\n    list(stat = tt$statistic, p = tt$p.value, md = if(!is.null(tt$estimate)) tt$estimate else median(b-a), m = tt$method);",
  "cluster": "library(cluster);\n    df <- as.data.frame({{data}});\n    colnames(df) <- c({{columns}});\n    df_scaled <- scale(df);\n    set.seed(123);\n    km <- kmeans(df_scaled, centers = {{k}}, nstart = 25);\n    list(\n        cluster = km$cluster,\n        centers = as.numeric(t(km$centers)),\n        cols = ncol(km$centers),\n        size = km$size,\n        withinss = km$withinss,\n        tot_withinss = km$tot.withinss,\n        betweenss = km$betweenss,\n        totss = km$totss\n    );",
  "anova2way": "y <- c({{y}});\n    f1 <- factor(c({{f1}}));\n    f2 <- factor(c({{f2}}));\n    mod <- aov(y ~ f1 * f2);\n    res <- summary(mod)[[1]];\n    list(\n        sources = rownames(res),\n        df = res$Df,\n        ss = res$\"Sum Sq\",\n        ms = res$\"Mean Sq\",\n        f = res$\"F value\",\n        p = res$\"Pr(>F)\"\n    );",
  "regression": "df <- as.data.frame({{data}});\n    colnames(df) <- c({{names}});\n    y_name <- colnames(df)[1];\n    f_str <- paste0(\"\\",
  "logistic": "df <- as.data.frame({{data}});\n    colnames(df) <- c({{names}});\n    y_name <- colnames(df)[1];\n    f_str <- paste0(\"\\",
  "sem": "library(lavaan);\n    df <- as.data.frame({{data}});\n    colnames(df) <- c({{columns}});\n    mod_str <- \"{{model}}\";\n    fit <- tryCatch({\n        sem(model = mod_str, data = df, std.lv = TRUE);\n    }, error = function(e) { stop(paste(\"Lavaan Error:\", e$message)) });\n    \n    fm <- fitMeasures(fit);\n    est <- parameterEstimates(fit, standardized = TRUE);\n    \n    list(\n        cfi = as.numeric(fm[\"cfi\"]),\n        tli = as.numeric(fm[\"tli\"]),\n        rmsea = as.numeric(fm[\"rmsea\"]),\n        srmr = as.numeric(fm[\"srmr\"]),\n        chisq = as.numeric(fm[\"chisq\"]),\n        df = as.numeric(fm[\"df\"]),\n        pvalue = as.numeric(fm[\"pvalue\"]),\n        est_list = split(est, seq(nrow(est)))\n    );"
};
