-- NCSStat Expert Article: SmartPLS 4 vs AMOS
INSERT INTO "public"."knowledge_articles" ("slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") 
VALUES (
    'smartpls-4-vs-amos-comparison', 
    'Advanced Statistics', 
    'SmartPLS 4 vs. AMOS: Cuộc Cách Mạng SEM Và Lựa Chọn Định Hình Tương Lai Luận Văn', 
    'SmartPLS 4 vs. AMOS: Shaping the Future of Your Structural Equation Modeling', 
    '💡 CHIẾN THUẬT: Đừng chọn phần mềm vì nó "dễ". Hãy chọn AMOS nếu bạn muốn khẳng định lý thuyết cũ (Theory Testing) và chọn SmartPLS 4 nếu bạn muốn khám phá nhân tố mới hoặc dự báo hành vi (Theory Building).', 
    'EXPERT STRATEGY: Choose AMOS for Theory Testing and SmartPLS 4 for Theory Building and Predictive Power. Match the tool to your research goal, not just ease of use.', 
    $$[
        {"h2_vi":"1. Nền tảng Triết học và Bản chất Toán học (CB-SEM vs PLS-SEM)","h2_en":"1. Epistemological Foundations: CB-SEM vs. PLS-SEM","content_vi":"Trong giới nghiên cứu, SEM được coi là đỉnh cao của phân tích. Tuy nhiên, hai phần mềm này đại diện cho hai trường phái đối lập:\n- **AMOS (CB-SEM):** Dựa trên ma trận hiệp phương sai. Triết lý của nó là sự **phù hợp (Fit)**. Nó giống như một chiếc khuôn đúc, kiểm tra xem dữ liệu của bạn có lọt vừa khuôn mẫu lý thuyết đã có từ trước hay không.\n- **SmartPLS 4 (PLS-SEM):** Dựa trên việc tối đa hóa phương sai được giải thích. Triết lý của nó là sự **dự báo (Prediction)**. Nó tập trung vào việc các biến của bạn giải thích được bao nhiêu phần trăm thực tế (R-Square). #AMOS #SmartPLS4 #Statistics","content_en":"AMOS (CB-SEM) focuses on 'Model Fit', acting as a judge of pre-existing theory. SmartPLS 4 (PLS-SEM) focuses on 'Prediction', maximizing the explained variance (R-Square) of your constructs. #SEM #ResearchMethods"},
        {"h2_vi":"2. Kích thước mẫu và Sự hội tụ của mô hình","h2_en":"2. Sample Size and Model Convergence","content_vi":"Đây là ranh giới sinh tử của nhiều luận văn:\n- **AMOS:** Cực kỳ kén dữ liệu. Bạn thường cần ít nhất 200-300 mẫu. Với mô hình phức tạp, AMOS thường xuyên báo lỗi 'Non-positive definite matrix', khiến bài nghiên cứu bị tắc nghẽn.\n- **SmartPLS 4:** Là một 'chiến binh' thực chiến. Nó có thể xử lý các mẫu nhỏ (thậm chí < 100) một cách ổn định nhờ thuật toán lặp từng phần. Đây là cứu cánh cho các nghiên cứu B2B hoặc khảo sát chuyên gia khó tiếp cận. #SampleSize #PhDLife","content_en":"AMOS requires large samples (200-300+) and often fails to converge on complex models. SmartPLS 4 thrives on smaller samples (< 100) and handles high complexity without computational crashes. #ExpertInsight"},
        {"h2_vi":"3. Cơn ác mộng Phân phối chuẩn (The Normality Trap)","h2_en":"3. The Normality Trap: Parametric vs. Non-parametric","content_vi":"- **AMOS:** Yêu cầu dữ liệu phải tuân thủ nghiêm ngặt **Phân phối chuẩn đa biến**. Nếu dữ liệu bị lệch (Skewness/Kurtosis cao), kết quả sẽ bị sai lệch hoàn toàn.\n- **SmartPLS 4:** Là phương pháp **phi tham số (Non-parametric)**. Nó không quan tâm dữ liệu có chuẩn hay không, cực kỳ phù hợp cho các khảo sát xã hội học thực tế tại Việt Nam nơi dữ liệu thường không bao giờ chuẩn tuyệt đối. #DataCleaning #Normality","content_en":"AMOS mandates multivariate normality, a rare find in real-world surveys. SmartPLS 4 is symmetry-free (non-parametric), making it resilient to non-normal data common in social science research."},
        {"h2_vi":"4. Thang đo Phản ánh (Reflective) vs Tạo thành (Formative)","h2_en":"4. Measurement Theory: Reflective vs. Formative Constructs","content_vi":"Một điểm chuyên sâu mà các hội đồng thường xoáy vào:\n- **AMOS:** Gần như chỉ xử lý tốt thang đo Phản ánh (biến tiềm ẩn tạo ra biểu hiện). Chạy thang đo Tạo thành trên AMOS là một cực hình kỹ thuật.\n- **SmartPLS 4:** Xung trận mạnh mẽ với cả hai loại thang đo. Việc định nghĩa biến Formative (biến số tạo nên nhân tố) cực kỳ đơn giản và chính xác. #FormativeScale #MeasurementModel","content_en":"AMOS struggles with Formative constructs. SmartPLS 4 handles both Reflective and Formative items with ease, making it superior for complex business and economic indices."},
        {"h2_vi":"5. Tính năng hiện đại: Consistent PLS và Bootstrapping","h2_en":"5. Modern Features: Consistent PLS and Fast Bootstrapping","content_vi":"SmartPLS 4 mang lại những bước tiến công nghệ vượt trội:\n- **Consistent PLS (PLSc):** Giúp kết quả PLS tương đương với kết quả của AMOS về mặt hàn lâm.\n- **Bootstrapping siêu tốc:** Tính toán hàng ngàn mẫu lặp trong giây lát để kiểm định p-value, giúp bạn tiết kiệm hàng giờ đồng hồ chờ đợi so với các phần mềm cũ. #FastBootstrapping #NCStat","content_en":"SmartPLS 4's Consistent PLS (PLSc) bridges the gap to CB-SEM results. Its lightning-fast Bootstrapping allows for rapid hypothesis testing and P-value generation. #StatisticalSoftware"},
        {"h2_vi":"6. Tiêu chuẩn công bố quốc tế: Scopus Q1/Q2 dùng gì?","h2_en":"6. Publication Standards: Scopus and WoS Trends","content_vi":"Trước đây AMOS là 'tiêu chuẩn vàng', nhưng hiện nay SmartPLS 4 đã chiếm lĩnh thị trường trong các lĩnh vực Quản trị, Marketing và Du lịch. Khi sử dụng SmartPLS 4, hãy chú ý báo cáo chỉ số **HTMT** (Thay thế Fornell-Larcker) và **PLSpredict** để nâng tầm bài báo lên chuẩn quốc tế. #Scopus #ISI #AcademicWriting","content_en":"While AMOS was the traditional gold standard, SmartPLS 4 has dominated Business and Social Science journals. Report HTMT and PLSpredict to ensure your paper meets the highest global standards. #HTMT #DiscriminantValidity"},
        {"h2_vi":"7. Bảng so sánh tổng hợp (Executive Summary)","h2_en":"7. Executive Summary Table","content_vi":"| Đặc điểm | AMOS (CB-SEM) | SmartPLS 4 (PLS-SEM) |\n|---|---|---|\n| Mục tiêu chính | Kiểm định/Khẳng định lý thuyết | Dự báo/Phát triển lý thuyết |\n| Kích thước mẫu | Lớn (thường > 200) | Nhỏ đến lớn (linh hoạt) |\n| Giả định dữ liệu | Phân phối chuẩn đa biến | Không yêu cầu phân phối chuẩn |\n| Thang đo | Chủ yếu là Phản ánh (Reflective) | Cả Phản ánh và Tạo thành (Formative) |\n| Độ phức tạp | Hạn chế với mô hình quá lớn | Xử lý cực tốt mô hình siêu phức tạp |\n| Chỉ số gác cổng | Model Fit (CFI, TLI, RMSEA) | R-Square, HTMT, f-Square |","content_en":"Short summary: AMOS is for confirming established theories with large, normal datasets. SmartPLS 4 is for exploring new relationships and predictive modeling with flexible data requirements."}
    ]$$
) ON CONFLICT (slug) DO UPDATE SET 
    title_vi = EXCLUDED.title_vi,
    title_en = EXCLUDED.title_en,
    expert_tip_vi = EXCLUDED.expert_tip_vi,
    expert_tip_en = EXCLUDED.expert_tip_en,
    content_structure = EXCLUDED.content_structure;
