-- NCSStat Expert Article: SEM
INSERT INTO "public"."knowledge_articles" ("slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") 
VALUES (
    'sem-structural-equation-modeling', 
    'Advanced Statistics', 
    'Mô hình SEM: Đỉnh cao của Phân tích Cấu trúc và Biến trung gian', 
    'Structural Equation Modeling (SEM): The Peak of Data Analysis', 
    'Đừng chỉ dừng lại ở tác động trực tiếp. SEM cho phép bạn khám phá các hiệu ứng gián tiếp (Mediation) cực kỳ tinh tế. Hãy luôn sử dụng Bootstrapping (5000 mẫu) để báo cáo có trọng lượng khoa học cao nhất.', 
    'Insight: Focus on Indirect Effects (Mediation). SEM allows for nuanced path analysis. Always employ Bootstrapping (5k samples) for top-tier journal submission standards.', 
    $$[
        {"h2_vi":"1. Quyền năng của SEM: Khi hồi quy truyền thống trở nên nhỏ bé","h2_en":"1. The Power of SEM Over OLS","content_vi":"Tại sao các tạp chí Q1 luôn yêu cầu **SEM (Structural Equation Modeling)**? Vì khác với hồi quy OLS, SEM xử lý được các sai số đo lường (measurement error) và cho phép kiểm định đồng thời hàng chục giả thuyết trong một sơ đồ mạng lưới phức tạp. Nếu mô hình của bạn có dạng A -> B -> C, SEM là 'vũ khí' duy nhất để đo lường trọn vẹn sức mạnh này. #StatModeling #Amos #SmartPLS","content_en":"Why do Q1 journals demand SEM? Unlike OLS, SEM accounts for measurement errors and tests dozens of hypotheses simultaneously within a complex network. For paths like A -> B -> C, SEM is the definitive weapon. #QuantitativeAnalysis #AdvancedStats"},
        {"h2_vi":"2. Chiến lược 2 bước: Từ Đo lường đến Cấu trúc","h2_en":"2. The Two-Step Strategy: Measurement to Structural","content_vi":"Một sai lầm phổ biến là nhảy thẳng vào chạy mô hình cấu trúc. Quy trình 'chuẩn hóa' bắt buộc phải là: \n1. **Mô hình đo lường (CFA):** Kiểm tra xem các biến quan sát có đo lường đúng nhân tố không.\n2. **Mô hình cấu trúc:** Kiểm tra các mũi tên tác động. ncsStat giúp bạn thực hiện quy trình này cực kỳ trực quan với biểu đồ Path Diagram tự động. #PathAnalysis #ResearchDesign","content_en":"A common rookie mistake is skipping straight to the structural model. The 'gold standard' workflow is: 1. CFA to ensure measurement integrity. 2. Structural path testing for hypotheses. ncsStat automates this with intuitive, publication-ready Path Diagrams. #AcademicFramework"},
        {"h2_vi":"3. Kiểm định Trung gian (Mediation) và Hiệu ứng Tổng thể","h2_en":"3. Mastering Mediation and Total Effects","content_vi":"Điểm hấp dẫn nhất của SEM là khả năng bóc tách hiệu ứng Gián tiếp. Câu hỏi không chỉ là 'A có tác động tới C không?', mà là 'A tác động tới C THÔNG QUA B như thế nào?'. Với tính năng **Bootstrapping** tích hợp, ncsStat sẽ cung cấp cho bạn khoảng tin cậy (Confidence Interval) để khẳng định biến trung gian có ý nghĩa thống kê hay không. #Mediation #Bootstrapping #NCStat","content_en":"The most captivating feature of SEM is isolating Indirect Effects. It's not just 'Does A affect C?', but 'How does A affect C THROUGH B?'. ncsStat's integrated Bootstrapping provides the necessary Confidence Intervals to validate mediation significance. #StatisticalInsights"}
    ]$$
) ON CONFLICT (slug) DO UPDATE SET title_vi = EXCLUDED.title_vi, content_structure = EXCLUDED.content_structure;
