-- NCSStat Expert Article: CFA
INSERT INTO "public"."knowledge_articles" ("slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") 
VALUES (
    'cfa-confirmatory-factor-analysis', 
    'Advanced Statistics', 
    'Phân tích CFA: Khẳng định sức mạnh thang đo và Giá trị hội tụ', 
    'Confirmatory Factor Analysis (CFA): Validity and Reliability', 
    'Đừng hoảng sợ khi RMSEA > 0.08. Hãy thử kiểm tra Modification Indices (MI) để tìm ra các cặp sai số tương quan tiềm năng, từ đó tối ưu hóa Model Fit cho bài nghiên cứu của bạn.', 
    'Expert Hack: Don''t panic if RMSEA > 0.08. Inspect Modification Indices (MI) to identify error covariances and optimize your Model Fit for publication.', 
    $$[
        {"h2_vi":"1. CFA vs EFA: Từ khám phá đến khẳng định sức mạnh","h2_en":"1. EFA vs. CFA: From Discovery to Confidence","content_vi":"Nếu EFA là cuộc dạo chơi để tìm kiếm cấu trúc nhân tố, thì **CFA (Confirmatory Factor Analysis)** chính là 'lời tuyên khế' khoa học. Bạn không còn đi tìm nữa, mà bạn đang dùng dữ liệu để khẳng định rằng: 'Thang đo này tuyệt đối chuẩn theo lý thuyết gốc'. Đây là bước đệm không thể thiếu trước khi bước vào thế giới của #SEM. #NCStat #StructuralEquationModeling","content_en":"While EFA is an exploratory journey, CFA is a scientific confirmation. You're leveraging data to prove your scale aligns perfectly with established theory. It's the mandatory gateway to the world of #SEM. #Psychometrics"},
        {"h2_vi":"2. Giải mã bộ chỉ số Model Fit: Khi nào mô hình 'Đẹp'?","h2_en":"2. Decoding Model Fit: The Scopus Standard","content_vi":"Một mô hình được Reviewer quốc tế chấp nhận thường phải vượt qua bộ 'tứ trụ': \n- **CFI & TLI** >= 0.90.\n- **RMSEA** <= 0.08.\n- **Chi-square/df** < 3.\nNếu mô hình của bạn 'xấu', ncsStat sẽ gợi ý các đường dẫn cần điều chỉnh để tối ưu hóa bộ chỉ số này mà không làm mất đi ý nghĩa lý thuyết. #ModelFit #StatHacks","content_en":"International reviewers look for the 'Big Four': CFI & TLI >= 0.90, RMSEA <= 0.08, and Chi-square/df < 3. If your model fails, ncsStat suggests paths to optimize indices without compromising theoretical integrity. #Amos #Lisrel"},
        {"h2_vi":"3. Giá trị hội tụ (AVE) và Tin cậy tổng hợp (CR)","h2_en":"3. Validity Gold Standards: AVE & CR","content_vi":"Độ tin cậy Cronbach's Alpha là chưa đủ. Trong CFA, bạn cần **CR > 0.7** và **AVE > 0.5**. Đây là chứng chỉ cho thấy các câu hỏi của bạn đang đo lường cực kỳ tập trung vào mục tiêu nghiên cứu. Nếu AVE thấp, hãy kiểm tra lại hệ số tải (Factor Loading) của từng biến, những biến < 0.5 chính là thủ phạm cần 'trình diện'. #Validity #ReliabilityAnalysis","content_en":"Alpha isn't enough for high-impact research. You need CR > 0.7 and AVE > 0.5. These are the certificates of focus. If AVE drops, hunt down variables with Factor Loadings < 0.5—they are the culprits weakening your construct. #DataScience"}
    ]$$
) ON CONFLICT (slug) DO UPDATE SET title_vi = EXCLUDED.title_vi, content_structure = EXCLUDED.content_structure;
