-- NCSStat Expert Article: Mediation vs Moderation
INSERT INTO "public"."knowledge_articles" ("slug", "category", "title_vi", "title_en", "expert_tip_vi", "expert_tip_en", "content_structure") 
VALUES (
    'mediation-vs-moderation-analysis', 
    'Advanced Statistics', 
    'Biến Trung Gian (Mediation) vs. Biến Điều Tiết (Moderation): Nghệ thuật Phân tích Đa chiều', 
    'Mediation vs. Moderation Analysis: Mastering Multidimensional Relationships', 
    '⚡ TRÁNH SAI LẦM: Biến trung gian giải thích TẠI SAO (Why), còn biến điều tiết trả lời câu hỏi KHI NÀO (When). Đừng nhầm lẫn giữa hai khái niệm này nếu không muốn bị hội đồng bác bỏ toàn bộ mô hình.', 
    'EXPERT HACK: Mediation explains WHY, while Moderation answers WHEN. Mixing them up is a fatal conceptual error in structural modeling.', 
    $$[
        {"h2_vi":"1. Biến Trung Gian (Mediation) là gì? Con đường của sự tác động","h2_en":"1. What is Mediation? The Path of Impact","content_vi":"Biến trung gian (Mediator) xuất hiện khi mối quan hệ giữa biến độc lập (X) và biến phụ thuộc (Y) không diễn ra trực tiếp mà thông qua một 'trạm trung chuyển' (M). Ví dụ: Quảng cáo (X) làm tăng Nhận thức thương hiệu (M), từ đó mới làm tăng Ý định mua hàng (Y). #Mediation #DirectEffect #IndirectEffect","content_en":"Mediation occurs when X affects Y through a third variable M. Example: Advertising (X) increases Brand Awareness (M), which in turn boosts Purchase Intention (Y). It’s the 'Why' of research. #PathAnalysis"},
        {"h2_vi":"2. Biến Điều Tiết (Moderation) là gì? Kẻ thay đổi cuộc chơi","h2_en":"2. What is Moderation? The Game Changer","content_vi":"Biến điều tiết (Moderator) là một biến làm thay đổi độ mạnh yếu hoặc hướng của mối quan hệ giữa X và Y. Nó trả lời cho câu hỏi: 'Mối quan hệ này có đúng với tất cả mọi người không?'. Ví dụ: Thu nhập (X) tác động đến Chi tiêu (Y) nhưng mức độ tác động này sẽ khác nhau tùy vào Giới tính (Biến điều tiết Z). #Moderation #InteractionEffect #ContextualResearch","content_en":"A Moderator (Z) changes the strength or direction of the X -> Y relationship. It answers 'Under what conditions?'. For instance, your income affects spending, but this effect might differ between Men and Women. #Interaction"},
        {"h2_vi":"3. Cách kiểm định Trung gian trên ncsStat: Baron & Kenny vs Bootstrapping","h2_en":"3. Testing Mediation: Beyond Baron & Kenny","content_vi":"Quên đi phương pháp cũ lỗi thời của Baron & Kenny (1986). Giới khoa học hiện đại yêu cầu kiểm định **Bootstrapping** (thường là 5000 mẫu lặp). ncsStat hỗ trợ bạn tính toán khoảng tin cậy (Confidence Interval). Nếu khoảng tin cậy không chứa giá trị 0, hiệu ứng trung gian chính thức có ý nghĩa thống kê! #PreacherAndHayes #BootstrappingCheck","content_en":"Forget the outdated Baron & Kenny method. Modern standards demand Bootstrapping (5000+ resamples). ncsStat provides the Confidence Interval (CI). If CI doesn't include 0, your mediation is significant! #MediationTest"},
        {"h2_vi":"4. Các loại Trung gian: Toàn phần, Một phần hay Đối nghịch?","h2_en":"4. Types of Mediation: Full vs. Partial","content_vi":"- **Trung gian toàn phần (Full Mediation):** X không còn tác động trực tiếp tới Y khi có M.\n- **Trung gian một phần (Partial Mediation):** X vẫn tác động tới Y ngay cả khi M hiện diện.\n- **Trung gian đối nghịch (Competitive Mediation):** Một trường hợp thú vị khi tác động gián tiếp ngược chiều với tác động trực tiếp. #AdvancedStatistics #HypothesisTesting","content_en":"Full Mediation: X no longer significantly impacts Y when M is present. Partial Mediation: Both direct and indirect paths are significant. Competitive Mediation: The indirect effect acts in opposition to the direct one."},
        {"h2_vi":"5. Kiểm định Điều tiết: Đồ thị tương tác (Interaction Plot)","h2_en":"5. Testing Moderation: The Interaction Plot","content_vi":"Để minh chứng cho biến điều tiết, bạn cần chỉ ra hệ số tương quan tích (Interaction Term) có ý nghĩa (p < 0.05). Nhưng để 'ăn điểm' hội đồng, bạn phải vẽ được đồ thị tương tác. ncsStat tự động xuất đồ thị các đường dốc (Slope) giúp bạn thấy rõ mối quan hệ X -> Y thay đổi thế nào khi biến điều tiết ở mức thấp vs. mức cao. #InteractionPlot #Visualization","content_en":"To prove moderation, the Interaction Term must be significant (p < 0.05). ncsStat generates the Slope plots, visually demonstrating how the X -> Y relationship shifts at different levels of the moderator. #GraphStats"}
    ]$$
) ON CONFLICT (slug) DO UPDATE SET 
    title_vi = EXCLUDED.title_vi,
    expert_tip_vi = EXCLUDED.expert_tip_vi,
    content_structure = EXCLUDED.content_structure;
